import { Order } from "./types";

export const mockOrders: Order[] = [
  // 1. RFQ Received — interactive demo entry point (tier-1 auto seating blanket release)
  {
    id: "ord-demo-005",
    orderNumber: "ORD-2026-0052",
    stage: "rfq_received",
    source: "email",
    createdAt: "2026-03-13T10:05:00Z",
    emailSubject: "Q2 blanket release — fastener kit for new program launch",
    customer: {
      id: "cust-demo-005",
      name: "Tom Wagner",
      email: "tom.wagner@apexseating.com",
      phone: "+1 (260) 563-2400",
      company: "Apex Seating Group",
      billingAddress: "1500 N Cass St, Wabash, IN 46992",
      shippingAddress: "Apex Wabash Plant, Dock 4, 1500 N Cass St, Wabash, IN 46992",
    },
    attachments: [
      {
        id: "att-demo-005",
        fileName: "Apex-Q2-Blanket-Release.pdf",
        mimeType: "application/pdf",
        size: 3_560,
        url: "/rfq-pacific-q2-2026.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-051",
        lineNumber: 1,
        rawText: "50,000 M8x25 Grade 10.9 zinc flange bolts (FB-M8X25-1090-ZN)",
        parsedSku: "FB-M8X25-1090-ZN",
        parsedProductName: "M8x25 Grade 10.9 Flange Bolt — Zinc",
        parsedQuantity: 50000,
        parsedUom: "units",
        parsedUnitPrice: 0.18,
        requestedDueDate: "2026-04-15",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "FB-M8X25-1090-ZN",
            catalogName: "M8x25 Grade 10.9 Flange Bolt — Zinc",
            catalogDescription: "Grade 10.9 metric flange bolt, M8 thread, 25mm length, zinc plated. JIS B 1189.",
            catalogPrice: 0.18,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-052",
        lineNumber: 2,
        rawText: "8,000 1/2-13 hex bolts grade 5 plain",
        parsedSku: null,
        parsedProductName: "1/2-13 Grade 5 Hex Bolt — Plain",
        parsedQuantity: 8000,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 62,
        matchedCatalogItems: [
          {
            catalogSku: "HEX-12-13X125-G5-PL",
            catalogName: '1/2"-13 x 1-1/4" Grade 5 Hex Bolt — Plain',
            catalogDescription: "Grade 5 imperial hex bolt, 1/2-13 thread, 1-1/4 inch length, plain finish.",
            catalogPrice: 0.21,
            catalogUom: "unit",
          },
          {
            catalogSku: "HEX-12-13X150-G5-PL",
            catalogName: '1/2"-13 x 1-1/2" Grade 5 Hex Bolt — Plain',
            catalogDescription: "Grade 5 imperial hex bolt, 1/2-13 thread, 1-1/2 inch length, plain finish.",
            catalogPrice: 0.24,
            catalogUom: "unit",
          },
          {
            catalogSku: "HEX-12-13X200-G5-PL",
            catalogName: '1/2"-13 x 2" Grade 5 Hex Bolt — Plain',
            catalogDescription: "Grade 5 imperial hex bolt, 1/2-13 thread, 2 inch length, plain finish.",
            catalogPrice: 0.29,
            catalogUom: "unit",
          },
        ],
        issues: [
          "No length specified — 1/2-13 stocked in 1-1/4\", 1-1/2\", and 2\" lengths",
          "Price varies $0.21 – $0.29/unit by length",
          "Need clarification before quoting",
        ],
      },
      {
        id: "li-demo-053",
        lineNumber: 3,
        rawText: "5,000 5/16 lag bolts hex 3 inch HDG",
        parsedSku: "LAG-516X3-HDG",
        parsedProductName: "5/16 Hex Lag Bolt 3 inch HDG",
        parsedQuantity: 5000,
        parsedUom: "units",
        parsedUnitPrice: 0.32,
        matchStatus: "conflict",
        confidence: 48,
        matchedCatalogItems: [
          {
            catalogSku: "LAG-516X3-HDG",
            catalogName: '5/16" x 3" Hex Lag Bolt — HDG',
            catalogDescription: "Hex head lag screw, 5/16 inch x 3 inch, hot-dip galvanized.",
            catalogPrice: 0.32,
            catalogUom: "unit",
          },
          {
            catalogSku: "LAG-516X3-ZN",
            catalogName: '5/16" x 3" Hex Lag Bolt — Zinc',
            catalogDescription: "Hex head lag screw, 5/16 inch x 3 inch, zinc plated.",
            catalogPrice: 0.24,
            catalogUom: "unit",
          },
        ],
        issues: [
          "RFQ specifies HDG, but standing blanket on this account is zinc (LAG-516X3-ZN)",
          "Price differs ($0.24 zinc vs $0.32 HDG) — confirm finish change is intentional",
          "Manual review required",
        ],
      },
      {
        id: "li-demo-054",
        lineNumber: 4,
        rawText: "4,000 nylock M10 fine thread ???",
        parsedSku: null,
        parsedProductName: "Nylock Nut M10 Fine Thread",
        parsedQuantity: 4000,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "M10 fine thread (M10x1.0) not in catalog — only M10 standard (M10x1.5) stocked",
          "Special-order item — needs supplier RFQ if customer confirms fine thread",
          "\"???\" in source suggests internal uncertainty — confirm with customer",
        ],
      },
      {
        id: "li-demo-055",
        lineNumber: 5,
        rawText: "25,000 M10x40 SHCS Grade 12.9 black oxide (SHCS-M10X40-1290-BO) — PPAP + 3.1",
        parsedSku: "SHCS-M10X40-1290-BO",
        parsedProductName: "M10x40 Socket Head Cap Screw Grade 12.9",
        parsedQuantity: 25000,
        parsedUom: "units",
        parsedUnitPrice: 0.42,
        requestedDueDate: "2026-04-20",
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "SHCS-M10X40-1290-BO",
            catalogName: "M10x40 Socket Head Cap Screw Grade 12.9",
            catalogDescription: "Grade 12.9 socket head cap screw, M10x40, black oxide. ISO 4762.",
            catalogPrice: 0.42,
            catalogUom: "unit",
          },
        ],
        issues: [
          "Customer requires full PPAP package + EN 10204 3.1 mill cert",
          "Route to engineering for PPAP doc generation",
        ],
      },
    ],
    totalItems: 5,
    parseConfidence: 88,
    parseMissingFields: ["price", "dueDate"],
    ingestionSourceLabel: "Outlook - RFQ PDF",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "rfq_received",
    },
  },

  // 2. Clarification Sent — email sent to customer, awaiting reply (ag equipment MRO restock)
  {
    id: "ord-demo-004",
    orderNumber: "ORD-2026-0051",
    stage: "clarification_requested",
    source: "email",
    createdAt: "2026-03-13T09:35:00Z",
    emailSubject: "RFQ — MRO fastener restock for ag equipment plant",
    customer: {
      id: "cust-demo-004",
      name: "James Whitfield",
      email: "james.whitfield@kuhnna.com",
      phone: "+1 (785) 825-3500",
      company: "Kuhn North America",
      billingAddress: "1501 W 7th St, Brodhead, WI 53520",
      shippingAddress: "Kuhn Brodhead Plant, Receiving Dock B, 1501 W 7th St, Brodhead, WI 53520",
    },
    attachments: [
      {
        id: "att-demo-004",
        fileName: "Kuhn-MRO-Restock-Mar.csv",
        mimeType: "text/csv",
        size: 312,
        url: "/rfq-acme-hydraulic-2026.csv",
      },
    ],
    lineItems: [
      {
        id: "li-demo-041",
        lineNumber: 1,
        rawText: "12,000 Hex Bolt M12x40 Grade 8.8 Zinc (HEX-M12X40-88-ZN) rev C",
        parsedSku: "HEX-M12X40-88-ZN",
        parsedProductName: "M12x40 Hex Bolt Grade 8.8 Zinc",
        parsedQuantity: 12000,
        parsedUom: "units",
        parsedUnitPrice: 0.42,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "HEX-M12X40-88-ZN",
            catalogName: "M12x40 Hex Bolt Grade 8.8 Zinc",
            catalogDescription: "Grade 8.8 hex bolt, M12 thread, 40mm length, zinc plated. DIN 933.",
            catalogPrice: 0.42,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-042",
        lineNumber: 2,
        rawText: "8,000 F436 Structural Washer 1/2 inch HDG (WS-F436-12-HDG)",
        parsedSku: "WS-F436-12-HDG",
        parsedProductName: 'F436 1/2" Structural Flat Washer',
        parsedQuantity: 8000,
        parsedUom: "units",
        parsedUnitPrice: 0.32,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "WS-F436-12-HDG",
            catalogName: 'F436 1/2" Structural Flat Washer — HDG',
            catalogDescription: "ASTM F436 Type 1 structural washer, 1/2 inch, hot-dip galvanized.",
            catalogPrice: 0.32,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-043",
        lineNumber: 3,
        rawText: '500 U-bolts 3/8"-16 — round or square bend?',
        parsedSku: "UB-38-RND",
        parsedProductName: 'U-Bolt 3/8"-16',
        parsedQuantity: 500,
        parsedUom: "units",
        parsedUnitPrice: 1.65,
        matchStatus: "partial",
        confidence: 68,
        matchedCatalogItems: [
          {
            catalogSku: "UB-38-RND",
            catalogName: '3/8"-16 U-Bolt Round Bend — HDG',
            catalogDescription: "Round-bend U-bolt for pipe and tubing, 3/8-16 thread, HDG.",
            catalogPrice: 1.65,
            catalogUom: "unit",
          },
          {
            catalogSku: "UB-38-SQR",
            catalogName: '3/8"-16 U-Bolt Square Bend — HDG',
            catalogDescription: "Square-bend U-bolt for square tubing, 3/8-16 thread, HDG.",
            catalogPrice: 1.95,
            catalogUom: "unit",
          },
        ],
        issues: [
          "Bend style not specified — round-bend (pipe) vs square-bend (square tube)",
          "Price differs ($1.65 round vs $1.95 square)",
        ],
      },
    ],
    totalItems: 3,
    parseConfidence: 91,
    parseMissingFields: [],
    ingestionSourceLabel: "Outlook - RFQ CSV",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "rfq_received",
      clarifications: [
        {
          questions: [
            "RFQ lists '500 U-bolts 3/8\"-16' without specifying bend style — round-bend (for pipe) or square-bend (for square tubing)?",
            "Requested due date for the F436 washers is 2026-03-29 — can you confirm this is firm?",
          ],
          emailSent: {
            to: "james.whitfield@kuhnna.com",
            subject: "ORD-2026-0051 — Clarification needed for 2 items",
            body: "Hi James,\n\nThank you for sending over the MRO fastener restock RFQ. We have a couple of questions before we can finalize pricing:\n\n1. The 500 U-bolts 3/8-16 — are these round-bend (for pipe) or square-bend (for square tubing)? Pricing differs by $0.30/unit.\n2. The due date on the F436 1/2 inch structural washers is listed as Mar 29 — is that firm?\n\nBest regards,\nHexa Sales Team",
            sentAt: "2026-03-13T09:50:00Z",
          },
        },
      ],
    },
  },

  // 3. Clarification Received — customer replied, ready for quote preparation (HVAC OEM fastener restock)
  {
    id: "ord-demo-001",
    orderNumber: "ORD-2026-0048",
    stage: "clarification_received",
    source: "email",
    createdAt: "2026-03-13T08:40:00Z",
    emailSubject: "RFQ-2026-1187 — March fastener restock for HVAC line",
    customer: {
      id: "cust-demo-003",
      name: "Elena Marsh",
      email: "elena.marsh@modine.com",
      phone: "+1 (270) 273-2645",
      company: "Modine Manufacturing",
      billingAddress: "1500 DeKoven Ave, Racine, WI 53403",
      shippingAddress: "Modine Trenton Plant, Receiving, 1900 Industrial Pkwy, Trenton, MO 64683",
    },
    attachments: [
      {
        id: "att-demo-001",
        fileName: "RFQ-Modine-1187-Mar.pdf",
        mimeType: "application/pdf",
        size: 3_285,
        url: "/rfq-northfield-march-2026.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-011",
        lineNumber: 1,
        rawText: "20,000 M6x16 Hex Bolt Grade 8.8 Zinc (HEX-M6X16-88-ZN) rev C",
        parsedSku: "HEX-M6X16-88-ZN",
        parsedProductName: "M6x16 Hex Bolt Grade 8.8 — Zinc",
        parsedQuantity: 20000,
        parsedUom: "units",
        parsedUnitPrice: 0.08,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "HEX-M6X16-88-ZN",
            catalogName: "M6x16 Hex Bolt Grade 8.8 — Zinc",
            catalogDescription: "Grade 8.8 metric hex bolt, M6 thread, 16mm length, zinc plated.",
            catalogPrice: 0.08,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-012",
        lineNumber: 2,
        rawText: "20,000 M6 Hex Nut Grade 8 Zinc (NUT-HEX-M6-ZN) rev B",
        parsedSku: "NUT-HEX-M6-ZN",
        parsedProductName: "M6 Hex Nut Grade 8 Zinc",
        parsedQuantity: 20000,
        parsedUom: "units",
        parsedUnitPrice: 0.03,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "NUT-HEX-M6-ZN",
            catalogName: "M6 Hex Nut Grade 8 Zinc",
            catalogDescription: "Grade 8 metric hex nut, M6, zinc plated. DIN 934.",
            catalogPrice: 0.03,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-013",
        lineNumber: 3,
        rawText: "5,000 #10 Self-Tapping Pan Head Phillips — A2 SS, 1 inch length",
        parsedSku: "ST-10X1-PAN-A2",
        parsedProductName: "#10 x 1 inch Pan Head Phillips Self-Tapper A2",
        parsedQuantity: 5000,
        parsedUom: "units",
        parsedUnitPrice: 0.11,
        requestedDueDate: "2026-03-30",
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "ST-10X1-PAN-A2",
            catalogName: "#10 x 1\" Pan Head Phillips Self-Tapper — A2",
            catalogDescription: "A2 stainless self-tapping screw, #10 x 1 inch, pan head Phillips drive.",
            catalogPrice: 0.11,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 97,
    ingestionSourceLabel: "Outlook - RFQ PDF",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "rfq_received",
      quoteNumber: "Q-2026-0048",
      clarifications: [
        {
          questions: [
            "RFQ lists '#10 Self-Tapping Pan Head' without specifying drive type — is this Phillips or Square (Robertson)?",
            "Requested due date for the M6 hex nuts is 2026-03-29 — can you confirm this is firm or if there is flexibility?",
          ],
          emailSent: {
            to: "elena.marsh@modine.com",
            subject: "RFQ-2026-1187 — Clarification needed for 2 items",
            body: "Hi Elena,\n\nThank you for sending over the HVAC line restock RFQ. We have a couple of questions before we can finalize pricing:\n\n1. The #10 self-tapping screws — Phillips or Square drive? You've used both on previous releases.\n2. The due date for the M6 hex nuts is listed as Mar 29 — is that firm?\n\nBest regards,\nHexa Sales Team",
            sentAt: "2026-03-13T09:00:00Z",
          },
          replyReceived: {
            body: "Hi, Phillips drive — same as the standing blanket. And yes, March 29 is firm on the nuts — they pair with last week's bolt release on Line 4.",
            receivedAt: "2026-03-13T09:25:00Z",
            parsedAnswers: [
              "Self-tapping screws are Phillips drive — confirmed",
              "M6 hex nut due date Mar 29 is firm — paired with Line 4 bolt release",
            ],
          },
        },
      ],
    },
  },

  // 4. Quote Sent — RFQ, quote already sent to customer (machine-builder fastener handwritten note)
  {
    id: "ord-demo-002",
    orderNumber: "ORD-2026-0049",
    stage: "quote_sent",
    source: "email",
    createdAt: "2026-03-13T08:55:00Z",
    emailSubject: "Quick RFQ — shop-floor fastener pull",
    customer: {
      id: "cust-demo-002",
      name: "Ravi Patel",
      email: "ravi.patel@greenfieldtooling.com",
      phone: "+1 (412) 778-4010",
      company: "Greenfield Tooling",
      billingAddress: "22 Foundry Lane, Pittsburgh, PA 15201",
      shippingAddress: "22 Foundry Lane, Dock 2, Pittsburgh, PA 15201",
    },
    attachments: [
      {
        id: "att-demo-002",
        fileName: "RFQ-Greenfield-Note.png",
        mimeType: "image/png",
        size: 2_998,
        url: "/rfq-summit-note.png",
      },
    ],
    lineItems: [
      {
        id: "li-demo-021",
        lineNumber: 1,
        rawText: "300 SHCS M6x20 A2 stainless rev B",
        parsedSku: "SHCS-M6X20-A2",
        parsedProductName: "Socket Head Cap Screw M6x20 A2",
        parsedQuantity: 300,
        parsedUom: "units",
        parsedUnitPrice: 0.22,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 93,
        matchedCatalogItems: [
          {
            catalogSku: "SHCS-M6X20-A2",
            catalogName: "Socket Head Cap Screw M6x20 — A2",
            catalogDescription: "A2-70 stainless socket head cap screw, M6x20. ISO 4762.",
            catalogPrice: 0.22,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-022",
        lineNumber: 2,
        rawText: "750 M10 flat washer DIN 125 zinc rev C",
        parsedSku: "WSH-FLT-M10-ZN",
        parsedProductName: "M10 Flat Washer DIN 125 Zinc",
        parsedQuantity: 750,
        parsedUom: "units",
        parsedUnitPrice: 0.04,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "WSH-FLT-M10-ZN",
            catalogName: "M10 Flat Washer DIN 125 — Zinc",
            catalogDescription: "DIN 125 Form A flat washer, M10, zinc plated.",
            catalogPrice: 0.04,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-023",
        lineNumber: 3,
        rawText: "200 Helicoil M8x1.25 tangless inserts",
        parsedSku: "HEL-M8X125-TL",
        parsedProductName: "Helicoil M8x1.25 Tangless Insert",
        parsedQuantity: 200,
        parsedUom: "units",
        parsedUnitPrice: 0.85,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "HEL-M8X125-TL",
            catalogName: "Helicoil M8x1.25 Tangless Insert",
            catalogDescription: "Tangless screw thread insert, M8x1.25, 1.5D length, 304 SS.",
            catalogPrice: 0.85,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 94,
    ingestionSourceLabel: "Outlook - RFQ",
    demoFlow: {
      scenario: "rfq_handwritten",
      stage: "quote_prepared",
      quoteNumber: "Q-2026-0049",
      quoteSummary: {
        quoteNumber: "Q-2026-0049",
        items: [
          { sku: "SHCS-M6X20-A2", name: "Socket Head Cap Screw M6x20 A2", qty: 300, unitPrice: 0.22 },
          { sku: "WSH-FLT-M10-ZN", name: "M10 Flat Washer DIN 125 Zinc", qty: 750, unitPrice: 0.04 },
          { sku: "HEL-M8X125-TL", name: "Helicoil M8x1.25 Tangless Insert", qty: 200, unitPrice: 0.85 },
        ],
        subtotal: 266.0,
        sentAt: "2026-03-13T08:40:00Z",
        sentTo: "ravi.patel@greenfieldtooling.com",
      },
    },
  },

  // ── Phone call orders ──────────────────────────────────────────────────

  // Sarah Chen — RFQ stage (items extracted from phone call, awaiting quote preparation)
  {
    id: "ord-call-2",
    orderNumber: "ORD-2026-0053",
    stage: "rfq_received",
    source: "phone",
    createdAt: "2026-03-12T16:32:00Z",
    emailSubject: "Phone Order – Sarah Chen (Stoughton Trailer Mfg.)",
    customer: {
      id: "cust-stoughton",
      name: "Sarah Chen",
      email: "s.chen@stoughtontrailer.com",
      phone: "+1 (608) 873-2500",
      company: "Stoughton Trailer Mfg.",
      billingAddress: "416 S Academy St, Stoughton, WI 53589",
      shippingAddress: "Stoughton Plant, Dock 7, 416 S Academy St, Stoughton, WI 53589",
    },
    attachments: [],
    lineItems: [
      { id: "s-li-1", lineNumber: 1, rawText: "1,000 M10x30 Hex Bolt Grade 8.8 Zinc — DIN 933", parsedSku: "HEX-M10X30-88-ZN", parsedProductName: "M10x30 Hex Bolt Grade 8.8", parsedQuantity: 1000, parsedUom: "units", parsedUnitPrice: 0.32, requestedDueDate: "20 Mar 2026", matchStatus: "confirmed", confidence: 97, matchedCatalogItems: [{ catalogSku: "HEX-M10X30-88-ZN", catalogName: "M10x30 Hex Bolt Grade 8.8 — Zinc", catalogDescription: "Grade 8.8 metric hex bolt, M10x30, zinc plated. DIN 933.", catalogPrice: 0.32, catalogUom: "unit" }], issues: [] },
      { id: "s-li-2", lineNumber: 2, rawText: "1,000 M10 Nylock Nut Grade 8 Zinc — DIN 985", parsedSku: "NUT-NYL-M10-ZN", parsedProductName: "M10 Nylock Nut Grade 8", parsedQuantity: 1000, parsedUom: "units", parsedUnitPrice: 0.14, requestedDueDate: "20 Mar 2026", matchStatus: "confirmed", confidence: 96, matchedCatalogItems: [{ catalogSku: "NUT-NYL-M10-ZN", catalogName: "M10 Nylock Nut Grade 8 — Zinc", catalogDescription: "Grade 8 nylon-insert lock nut, M10, zinc plated. DIN 985.", catalogPrice: 0.14, catalogUom: "unit" }], issues: [] },
      { id: "s-li-3", lineNumber: 3, rawText: "2,000 M10 Flat Washer DIN 125 Zinc", parsedSku: "WSH-FLT-M10-ZN", parsedProductName: "M10 Flat Washer DIN 125", parsedQuantity: 2000, parsedUom: "units", parsedUnitPrice: 0.04, requestedDueDate: "20 Mar 2026", matchStatus: "confirmed", confidence: 98, matchedCatalogItems: [{ catalogSku: "WSH-FLT-M10-ZN", catalogName: "M10 Flat Washer DIN 125 — Zinc", catalogDescription: "DIN 125 Form A flat washer, M10, zinc plated.", catalogPrice: 0.04, catalogUom: "unit" }], issues: [] },
      { id: "s-li-4", lineNumber: 4, rawText: "500 Socket Head Cap Screw M6x20 A2 stainless", parsedSku: "SHCS-M6X20-A2", parsedProductName: "Socket Head Cap Screw M6x20 A2", parsedQuantity: 500, parsedUom: "units", parsedUnitPrice: 0.22, requestedDueDate: "20 Mar 2026", matchStatus: "confirmed", confidence: 95, matchedCatalogItems: [{ catalogSku: "SHCS-M6X20-A2", catalogName: "Socket Head Cap Screw M6x20 — A2", catalogDescription: "A2-70 stainless socket head cap screw, M6x20. ISO 4762.", catalogPrice: 0.22, catalogUom: "unit" }], issues: [] },
      { id: "s-li-5", lineNumber: 5, rawText: "250 Lag Screw 3/8 by 4 inch HDG", parsedSku: "LAG-38X4-HDG", parsedProductName: 'Lag Screw 3/8" x 4" HDG', parsedQuantity: 250, parsedUom: "units", parsedUnitPrice: 0.48, requestedDueDate: "20 Mar 2026", matchStatus: "confirmed", confidence: 94, matchedCatalogItems: [{ catalogSku: "LAG-38X4-HDG", catalogName: '3/8" x 4" Hex Lag Screw — HDG', catalogDescription: "Hex head lag screw, 3/8 inch x 4 inch, hot-dip galvanized.", catalogPrice: 0.48, catalogUom: "unit" }], issues: [] },
      { id: "s-li-6", lineNumber: 6, rawText: "100 Stainless Spring Washer M12 — A2 Stainless", parsedSku: "WSH-SPR-M12-SS", parsedProductName: "Stainless Spring Washer M12", parsedQuantity: 100, parsedUom: "units", parsedUnitPrice: 0.18, requestedDueDate: "20 Mar 2026", matchStatus: "confirmed", confidence: 98, matchedCatalogItems: [{ catalogSku: "WSH-SPR-M12-SS", catalogName: "Stainless Spring Washer M12", catalogDescription: "A2 stainless steel spring washer, M12. DIN 127.", catalogPrice: 0.18, catalogUom: "unit" }], issues: [] },
      { id: "s-li-7", lineNumber: 7, rawText: "200 Helicoil M8x1.25 tangless inserts", parsedSku: "HEL-M8X125-TL", parsedProductName: "Helicoil M8x1.25 Tangless Insert", parsedQuantity: 200, parsedUom: "units", parsedUnitPrice: 0.85, requestedDueDate: "20 Mar 2026", matchStatus: "confirmed", confidence: 96, matchedCatalogItems: [{ catalogSku: "HEL-M8X125-TL", catalogName: "Helicoil M8x1.25 Tangless Insert", catalogDescription: "Tangless screw thread insert, M8x1.25, 1.5D length, 304 SS.", catalogPrice: 0.85, catalogUom: "unit" }], issues: [] },
    ],
    totalItems: 7,
    dueDate: "20 Mar 2026",
    shipTo: "Stoughton Plant",
    paymentTerms: "Net 30",
    parseConfidence: 96,
    parseMissingFields: [],
    ingestionSourceLabel: "Phone Call",
    demoFlow: {
      scenario: "dynamic",
      stage: "rfq_received",
    },
  },

  // Raj Patel — PO Received stage (RFQ ✓ → Quote sent via email ✓ → PO received)
  {
    id: "ord-call-3",
    orderNumber: "ORD-2026-0054",
    stage: "po_received",
    source: "phone",
    createdAt: "2026-02-21T11:15:00Z",
    emailSubject: "Phone Order – Raj Patel (Modine Manufacturing) — HVAC fastener restock",
    customer: {
      id: "cust-modine-raj",
      name: "Raj Patel",
      email: "r.patel@modine.com",
      phone: "+1 (270) 273-2645",
      company: "Modine Manufacturing",
      billingAddress: "1500 DeKoven Ave, Racine, WI 53403",
      shippingAddress: "Modine Trenton Plant, Receiving, 1900 Industrial Pkwy, Trenton, MO 64683",
    },
    attachments: [],
    lineItems: [
      { id: "r-li-1", lineNumber: 1, rawText: "2,000 M6 Zinc-Plated Flat Washer – Zinc Plated, DIN 125A", parsedSku: "WSH-M6-ZP", parsedProductName: "M6 Zinc-Plated Flat Washer", parsedQuantity: 2000, parsedUom: "pieces", parsedUnitPrice: 0.04, requestedDueDate: "7 Mar 2025", matchStatus: "confirmed", confidence: 98, matchedCatalogItems: [], issues: [] },
      { id: "r-li-2", lineNumber: 2, rawText: "800 Self-Tapping Screw 4.8x25mm – Pozi Pan Head, Zinc Plated", parsedSku: "SCR-ST-48x25-ZP", parsedProductName: "Self-Tapping Screw 4.8x25mm", parsedQuantity: 800, parsedUom: "pieces", parsedUnitPrice: 0.09, requestedDueDate: "7 Mar 2025", matchStatus: "confirmed", confidence: 96, matchedCatalogItems: [], issues: [] },
      { id: "r-li-3", lineNumber: 3, rawText: "50 metres Copper Tube 15mm Type A – BS EN 1057, Type A (Hard Drawn)", parsedSku: "COP-15-TYP-A", parsedProductName: "Copper Tube 15mm Type A", parsedQuantity: 50, parsedUom: "metres", parsedUnitPrice: 8.20, requestedDueDate: "7 Mar 2025", matchStatus: "confirmed", confidence: 95, matchedCatalogItems: [], issues: [] },
      { id: "r-li-4", lineNumber: 4, rawText: "30 Brass Compression Fitting 15mm – DZR Brass, BS EN 1254", parsedSku: "FIT-BRS-COMP-15", parsedProductName: "Brass Compression Fitting 15mm", parsedQuantity: 30, parsedUom: "pieces", parsedUnitPrice: 2.45, requestedDueDate: "7 Mar 2025", matchStatus: "confirmed", confidence: 97, matchedCatalogItems: [], issues: [] },
    ],
    totalItems: 4,
    poNumber: "PO-TS-2025-0089",
    dueDate: "7 Mar 2025",
    shipTo: "Leeds Depot",
    paymentTerms: "Net 30",
    parseConfidence: 97,
    parseMissingFields: [],
    ingestionSourceLabel: "Phone Call",
    demoFlow: {
      scenario: "dynamic",
      stage: "po_received",
      quoteNumber: "Q-2025-0054",
      poNumber: "PO-TS-2025-0089",
      quoteSummary: {
        quoteNumber: "Q-2025-0054",
        items: [
          { sku: "WSH-M6-ZP", name: "M6 Zinc-Plated Flat Washer", qty: 2000, unitPrice: 0.04 },
          { sku: "SCR-ST-48x25-ZP", name: "Self-Tapping Screw 4.8x25mm", qty: 800, unitPrice: 0.09 },
          { sku: "COP-15-TYP-A", name: "Copper Tube 15mm Type A", qty: 50, unitPrice: 8.20 },
          { sku: "FIT-BRS-COMP-15", name: "Brass Compression Fitting 15mm", qty: 30, unitPrice: 2.45 },
        ],
        subtotal: 635.50,
        sentAt: "2025-02-21T14:20:00Z",
        sentTo: "r.patel@thorntonsupplies.co.uk",
      },
      poConfirmation: {
        poNumber: "PO-TS-2025-0089",
        receivedAt: "2025-02-22T09:45:00Z",
        matchesQuote: true,
      },
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price" as const, matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity" as const, matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate" as const, matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
        ],
      },
    },
  },

  // Emily Watson — PO Received stage (RFQ ✓ → Quote sent via email ✓ → PO received)
  {
    id: "ord-call-4",
    orderNumber: "ORD-2026-0055",
    stage: "po_received",
    source: "phone",
    createdAt: "2026-02-19T09:20:00Z",
    emailSubject: "Phone Order – Emily Watson (Apex Seating) — structural fastener kit",
    customer: {
      id: "cust-apex-emily",
      name: "Emily Watson",
      email: "e.watson@apexseating.com",
      phone: "+1 (260) 563-2400",
      company: "Apex Seating Group",
      billingAddress: "1500 N Cass St, Wabash, IN 46992",
      shippingAddress: "Apex Wabash Plant, Dock 4, 1500 N Cass St, Wabash, IN 46992",
    },
    attachments: [],
    lineItems: [
      { id: "e-li-1", lineNumber: 1, rawText: "400 SS Socket Head Cap Screw M8x40 – A2 Stainless Steel, DIN 912", parsedSku: "SCR-SHC-M8x40-SS", parsedProductName: "SS Socket Head Cap Screw M8x40", parsedQuantity: 400, parsedUom: "pieces", parsedUnitPrice: 0.28, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 97, matchedCatalogItems: [], issues: [] },
      { id: "e-li-2", lineNumber: 2, rawText: "250 High-Tensile Flange Bolt M10x30 – Grade 8.8, Zinc Flake Coated", parsedSku: "BLT-FLG-M10x30-HT", parsedProductName: "High-Tensile Flange Bolt M10x30", parsedQuantity: 250, parsedUom: "pieces", parsedUnitPrice: 0.45, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 95, matchedCatalogItems: [], issues: [] },
      { id: "e-li-3", lineNumber: 3, rawText: "100 metres Mild Steel Angle 50x50x5mm – S275JR Grade, EN 10056", parsedSku: "STL-ANG-50x50x5", parsedProductName: "Mild Steel Angle 50x50x5mm", parsedQuantity: 100, parsedUom: "metres", parsedUnitPrice: 6.80, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 94, matchedCatalogItems: [], issues: [] },
      { id: "e-li-4", lineNumber: 4, rawText: "80 metres Square Hollow Section 40x40x3mm – S275JR Grade, EN 10219", parsedSku: "STL-SHS-40x40x3", parsedProductName: "Square Hollow Section 40x40x3mm", parsedQuantity: 80, parsedUom: "metres", parsedUnitPrice: 9.50, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 93, matchedCatalogItems: [], issues: [] },
      { id: "e-li-5", lineNumber: 5, rawText: "200 Rubber Anti-Vibration Mount M8 – Male-Female, Shore 55A", parsedSku: "MNT-AVB-M8-RBR", parsedProductName: "Rubber Anti-Vibration Mount M8", parsedQuantity: 200, parsedUom: "pieces", parsedUnitPrice: 3.60, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 92, matchedCatalogItems: [], issues: [] },
      { id: "e-li-6", lineNumber: 6, rawText: "50 Stainless Hose Clamp 25-40mm – W4 Band, AISI 304", parsedSku: "CLP-HSE-25-40-SS", parsedProductName: "Stainless Hose Clamp 25-40mm", parsedQuantity: 50, parsedUom: "pieces", parsedUnitPrice: 0.95, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 96, matchedCatalogItems: [], issues: [] },
      { id: "e-li-7", lineNumber: 7, rawText: "150 Nyloc Nut M10 Zinc Plated – DIN 985, Class 8", parsedSku: "NUT-NYL-M10-ZP", parsedProductName: "Nyloc Nut M10 Zinc Plated", parsedQuantity: 150, parsedUom: "pieces", parsedUnitPrice: 0.12, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 98, matchedCatalogItems: [], issues: [] },
      { id: "e-li-8", lineNumber: 8, rawText: "500 Cable Tie 300mm Black – Nylon 66, UV Stabilised", parsedSku: "CBL-TIE-300-BLK", parsedProductName: "Cable Tie 300mm Black", parsedQuantity: 500, parsedUom: "pieces", parsedUnitPrice: 0.03, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 99, matchedCatalogItems: [], issues: [] },
      { id: "e-li-9", lineNumber: 9, rawText: "20 litres Cutting Fluid Concentrate – Semi-Synthetic, Water Soluble", parsedSku: "FLD-CUT-CONC", parsedProductName: "Cutting Fluid Concentrate", parsedQuantity: 20, parsedUom: "litres", parsedUnitPrice: 14.50, requestedDueDate: "25 Mar 2025", matchStatus: "confirmed", confidence: 94, matchedCatalogItems: [], issues: [] },
    ],
    totalItems: 9,
    poNumber: "PO-BL-2025-0412",
    dueDate: "25 Mar 2025",
    shipTo: "Birmingham Site",
    paymentTerms: "Net 60",
    parseConfidence: 95,
    parseMissingFields: [],
    ingestionSourceLabel: "Phone Call",
    demoFlow: {
      scenario: "dynamic",
      stage: "po_received",
      quoteNumber: "Q-2025-0055",
      poNumber: "PO-BL-2025-0412",
      quoteSummary: {
        quoteNumber: "Q-2025-0055",
        items: [
          { sku: "SCR-SHC-M8x40-SS", name: "SS Socket Head Cap Screw M8x40", qty: 400, unitPrice: 0.28 },
          { sku: "BLT-FLG-M10x30-HT", name: "High-Tensile Flange Bolt M10x30", qty: 250, unitPrice: 0.45 },
          { sku: "STL-ANG-50x50x5", name: "Mild Steel Angle 50x50x5mm", qty: 100, unitPrice: 6.80 },
          { sku: "STL-SHS-40x40x3", name: "Square Hollow Section 40x40x3mm", qty: 80, unitPrice: 9.50 },
          { sku: "MNT-AVB-M8-RBR", name: "Rubber Anti-Vibration Mount M8", qty: 200, unitPrice: 3.60 },
          { sku: "CLP-HSE-25-40-SS", name: "Stainless Hose Clamp 25-40mm", qty: 50, unitPrice: 0.95 },
          { sku: "NUT-NYL-M10-ZP", name: "Nyloc Nut M10 Zinc Plated", qty: 150, unitPrice: 0.12 },
          { sku: "CBL-TIE-300-BLK", name: "Cable Tie 300mm Black", qty: 500, unitPrice: 0.03 },
          { sku: "FLD-CUT-CONC", name: "Cutting Fluid Concentrate", qty: 20, unitPrice: 14.50 },
        ],
        subtotal: 2755.00,
        sentAt: "2025-02-19T15:10:00Z",
        sentTo: "e.watson@bartonlogistics.co.uk",
      },
      poConfirmation: {
        poNumber: "PO-BL-2025-0412",
        receivedAt: "2025-02-20T11:30:00Z",
        matchesQuote: true,
      },
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price" as const, matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity" as const, matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate" as const, matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
        ],
      },
    },
  },

  // Marcus O'Brien — RFQ stage (items extracted from phone call, awaiting quote preparation)
  {
    id: "ord-call-5",
    orderNumber: "ORD-2026-0056",
    stage: "rfq_received",
    source: "phone",
    createdAt: "2026-02-17T15:45:00Z",
    emailSubject: "Phone Order – Marcus O'Brien (Greenfield Tooling) — quick fastener pull",
    customer: {
      id: "cust-greenfield",
      name: "Marcus O'Brien",
      email: "m.obrien@greenfieldtooling.com",
      phone: "+1 (412) 778-4010",
      company: "Greenfield Tooling",
      billingAddress: "22 Foundry Lane, Pittsburgh, PA 15201",
      shippingAddress: "22 Foundry Lane, Dock 2, Pittsburgh, PA 15201",
    },
    attachments: [],
    lineItems: [
      { id: "m-li-1", lineNumber: 1, rawText: "120 DIN 6921 Flanged Hex Bolt M12x50 – Grade 10.9, DIN 6921", parsedSku: "BLT-FHX-M12x50", parsedProductName: "DIN 6921 Flanged Hex Bolt M12x50", parsedQuantity: 120, parsedUom: "pieces", parsedUnitPrice: 0.72, requestedDueDate: "28 Feb 2025", matchStatus: "confirmed", confidence: 97, matchedCatalogItems: [{ catalogSku: "BLT-FHX-M12x50", catalogName: "DIN 6921 Flanged Hex Bolt M12x50", catalogDescription: "Grade 10.9 flanged hex bolt, M12x50mm, DIN 6921", catalogPrice: 0.72, catalogUom: "piece" }], issues: [] },
      { id: "m-li-2", lineNumber: 2, rawText: "60 PTFE Thread Seal Tape 12mm – 12mm x 12m, BS 7786", parsedSku: "TPE-PTFE-12", parsedProductName: "PTFE Thread Seal Tape 12mm", parsedQuantity: 60, parsedUom: "rolls", parsedUnitPrice: 1.15, requestedDueDate: "28 Feb 2025", matchStatus: "confirmed", confidence: 98, matchedCatalogItems: [{ catalogSku: "TPE-PTFE-12", catalogName: "PTFE Thread Seal Tape 12mm", catalogDescription: "PTFE thread seal tape, 12mm x 12m, BS 7786", catalogPrice: 1.15, catalogUom: "roll" }], issues: [] },
      { id: "m-li-3", lineNumber: 3, rawText: "10 D2 Tool Steel Blank 100x50x20mm – D2 Grade, Precision Ground, As-Ground Finish", parsedSku: "STL-D2-100x50x20", parsedProductName: "D2 Tool Steel Blank 100x50x20mm", parsedQuantity: 10, parsedUom: "pieces", parsedUnitPrice: 34.00, requestedDueDate: "28 Feb 2025", matchStatus: "confirmed", confidence: 95, matchedCatalogItems: [{ catalogSku: "STL-D2-100x50x20", catalogName: "D2 Tool Steel Blank 100x50x20mm", catalogDescription: "D2 grade precision ground tool steel blank, as-ground finish", catalogPrice: 34.00, catalogUom: "piece" }], issues: [] },
    ],
    totalItems: 3,
    dueDate: "28 Feb 2025",
    shipTo: "Bristol Unit",
    paymentTerms: "Net 30",
    parseConfidence: 97,
    parseMissingFields: [],
    ingestionSourceLabel: "Phone Call",
    demoFlow: {
      scenario: "dynamic",
      stage: "rfq_received",
    },
  },

  // 5. In Manufacturing — pushed to MRP, shipment created, awaiting production
  {
    id: "ord-003",
    orderNumber: "ORD-2026-0045",
    stage: "shipped",
    source: "email",
    createdAt: "2026-02-25T11:00:00Z",
    emailSubject: "Re: Quarterly Fastener Supply — M12 hex bolts + F436 washers",
    customer: {
      id: "cust-003",
      name: "Marcus Rivera",
      email: "m.rivera@toplinehardware.com",
      phone: "(503) 321-0987",
      company: "Topline Hardware LLC",
      billingAddress: "78 Main Street, Portland, OR 97201",
      shippingAddress: "900 Distribution Way, Portland, OR 97220",
    },
    attachments: [
      {
        id: "att-003",
        fileName: "PO-2026-0299-Topline.pdf",
        mimeType: "application/pdf",
        size: 3_736,
        url: "/po-topline-supply-q1.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-020",
        lineNumber: 1,
        rawText: "12,000 M12x40 Hex Bolt Grade 8.8 Zinc HEX-M12X40-88-ZN",
        parsedSku: "HEX-M12X40-88-ZN",
        parsedProductName: "M12x40 Hex Bolt Grade 8.8 — Zinc",
        parsedQuantity: 12000,
        parsedUom: "units",
        parsedUnitPrice: 0.42,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "HEX-M12X40-88-ZN",
            catalogName: "M12x40 Hex Bolt Grade 8.8 — Zinc",
            catalogDescription: "Grade 8.8 metric hex bolt, M12 thread, 40mm length, zinc plated.",
            catalogPrice: 0.42,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-021",
        lineNumber: 2,
        rawText: '8,000 F436 1/2" Structural Washer HDG WS-F436-12-HDG',
        parsedSku: "WS-F436-12-HDG",
        parsedProductName: 'F436 1/2" Structural Flat Washer',
        parsedQuantity: 8000,
        parsedUom: "units",
        parsedUnitPrice: 0.32,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "WS-F436-12-HDG",
            catalogName: 'F436 1/2" Structural Flat Washer — HDG',
            catalogDescription: "ASTM F436 Type 1 structural washer, 1/2 inch, hot-dip galvanized.",
            catalogPrice: 0.32,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-022",
        lineNumber: 3,
        rawText: '4,000 Heavy Hex Nut 1/2-13 HDG NUT-HVY-12-13',
        parsedSku: "NUT-HVY-12-13",
        parsedProductName: '1/2"-13 Heavy Hex Nut — HDG',
        parsedQuantity: 4000,
        parsedUom: "units",
        parsedUnitPrice: 0.18,
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "NUT-HVY-12-13",
            catalogName: '1/2"-13 Heavy Hex Nut — HDG',
            catalogDescription: "ASTM A563 Grade DH heavy hex nut, 1/2-13, hot-dip galvanized.",
            catalogPrice: 0.18,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-023",
        lineNumber: 4,
        rawText: "60 SHCS M6x20 A2 SHCS-M6X20-A2",
        parsedSku: "SHCS-M6X20-A2",
        parsedProductName: "Socket Head Cap Screw M6x20 A2",
        parsedQuantity: 60,
        parsedUom: "each",
        parsedUnitPrice: 0.22,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "SHCS-M6X20-A2",
            catalogName: "Socket Head Cap Screw M6x20 — A2",
            catalogDescription: "A2-70 stainless socket head cap screw, M6x20. ISO 4762.",
            catalogPrice: 0.22,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 4,
    poNumber: "PO-2026-0299",
    dueDate: "12 Mar 2026",
    shipTo: "900 Distribution Way, Portland, OR 97220",
    shipVia: "FedEx Economy",
    paymentTerms: "Net 30",
    parseConfidence: 96,
    parseMissingFields: [],
    mrpRoutedAt: "2026-02-25T11:01:00Z",
    ingestionSourceLabel: "email:attachment",
    shipmentSummary: {
      shipmentId: "shp-mock-003",
      status: "shipment_created",
      carrier: "fedex",
      trackingNumber: "794644790132",
      estimatedDelivery: "2026-03-18",
      latestEventAt: "2026-03-10T14:30:00Z",
    },
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0038",
      poNumber: "PO-2026-0299",
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price", matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity", matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate", matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
          { field: "drawingRev", matches: true, quoteValue: "Revisions matched", incomingValue: "Revisions matched" },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0038",
        items: [
          { sku: "HEX-M12X40-88-ZN", name: "M12x40 Hex Bolt Grade 8.8 Zinc", qty: 12000, unitPrice: 0.42 },
          { sku: "WS-F436-12-HDG", name: 'F436 1/2" Structural Washer HDG', qty: 8000, unitPrice: 0.32 },
          { sku: "NUT-HVY-12-13", name: '1/2"-13 Heavy Hex Nut HDG', qty: 4000, unitPrice: 0.18 },
          { sku: "SHCS-M6X20-A2", name: "Socket Head Cap Screw M6x20 A2", qty: 60, unitPrice: 0.22 },
        ],
        subtotal: 8333.20,
        sentAt: "2026-02-22T10:00:00Z",
        sentTo: "m.rivera@toplinehardware.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0299",
        receivedAt: "2026-02-24T14:30:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-02-25T11:01:00Z",
        erpOrderId: "ERP-2026-0299",
      },
      erpSync: {
        state: "acknowledged",
        timeline: [
          { label: "PO parsed from email attachment", state: "queued", at: "2026-02-25T11:00:12Z" },
          { label: "PO matched against quote Q-2026-0038", state: "sent", at: "2026-02-25T11:00:45Z" },
          { label: "ERP order acknowledged", state: "acknowledged", at: "2026-02-25T11:01:00Z" },
        ],
      },
    },
  },

  // Quote Builder demo — BOM Review stage
  {
    id: "ord-demo-bom-001",
    orderNumber: "ORD-2026-0060",
    stage: "bom_review",
    source: "email",
    orderType: "quote_builder",
    createdAt: "2026-03-27T09:15:00Z",
    emailSubject: "RFQ — Structural fastener BOM (TC-bolt assembly + F436 + heavy hex)",
    customer: {
      id: "cust-bom-001",
      name: "Rachel Kim",
      email: "rachel.kim@kuhnna.com",
      phone: "+1 (785) 825-3500",
      company: "Kuhn North America",
      billingAddress: "1501 W 7th St, Brodhead, WI 53520",
      shippingAddress: "Kuhn Brodhead Plant, Receiving, 1501 W 7th St, Brodhead, WI 53520",
    },
    attachments: [
      { id: "att-bom-001", fileName: "Pump-Station-Assembly-Drawing.pdf", mimeType: "application/pdf", size: 8200, url: "/rfq-handwritten-note.pdf" },
      { id: "att-bom-002", fileName: "Valve-Package-Specs.pdf", mimeType: "application/pdf", size: 4100, url: "/po-match-q-2026-0047.pdf" },
    ],
    lineItems: [
      {
        id: "li-bom-001",
        lineNumber: 1,
        rawText: "10x Check Valve Assembly 3-inch SS (VA-300)",
        parsedSku: "VA-300",
        parsedProductName: "Check Valve Assembly 3-inch SS",
        parsedQuantity: 10,
        parsedUom: "units",
        parsedUnitPrice: 210.00,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [{ catalogSku: "VA-300", catalogName: "Check Valve Assembly 3-inch SS", catalogDescription: "3-inch stainless steel check valve for heavy industrial applications.", catalogPrice: 210.00, catalogUom: "unit" }],
        issues: [],
        bomComponents: [
          { id: "li-bom-001-bom-0", catalogSku: "SF-3-150", name: 'SS Flange 3" 150lb', quantity: 2, uom: "each", unitCost: 18.75, isCustom: false },
          { id: "li-bom-001-bom-1", catalogSku: "GK-FL-3", name: 'Flange Gasket Kit 3"', quantity: 2, uom: "set", unitCost: 3.50, isCustom: false },
          { id: "li-bom-001-bom-2", catalogSku: "HB-M10-40", name: "Hex Bolt M10x40mm 25-Pack", quantity: 1, uom: "pack", unitCost: 4.50, isCustom: false },
          { id: "li-bom-001-bom-3", catalogSku: "RS-HD-10", name: "Rubber Seal Heavy Duty 10-Pack", quantity: 1, uom: "pack", unitCost: 22.00, isCustom: false },
          { id: "li-bom-001-bom-4", catalogSku: null, name: "Valve Body Casting 3\" SS", quantity: 1, uom: "each", unitCost: 85.00, isCustom: true },
        ],
      },
      {
        id: "li-bom-002",
        lineNumber: 2,
        rawText: "5x Centrifugal Pump Motor 2HP (PM-CEN-2HP)",
        parsedSku: "PM-CEN-2HP",
        parsedProductName: "Centrifugal Pump Motor 2HP",
        parsedQuantity: 5,
        parsedUom: "units",
        parsedUnitPrice: 450.00,
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [{ catalogSku: "PM-CEN-2HP", catalogName: "Centrifugal Pump Motor 2HP", catalogDescription: "2HP electric motor for centrifugal pumps, TEFC, 3450 RPM.", catalogPrice: 450.00, catalogUom: "unit" }],
        issues: [],
        bomComponents: [
          { id: "li-bom-002-bom-0", catalogSku: "BB-6205", name: "Ball Bearing 6205-2RS", quantity: 2, uom: "each", unitCost: 5.10, isCustom: false },
          { id: "li-bom-002-bom-1", catalogSku: "PS-KIT-STD", name: "Pump Seal Kit Standard", quantity: 1, uom: "kit", unitCost: 28.00, isCustom: false },
          { id: "li-bom-002-bom-2", catalogSku: "EW-12-100", name: "Electrical Wire 12AWG 100ft", quantity: 1, uom: "roll", unitCost: 35.00, isCustom: false },
          { id: "li-bom-002-bom-3", catalogSku: null, name: "Motor Housing Cast Iron 2HP", quantity: 1, uom: "each", unitCost: 180.00, isCustom: true },
          { id: "li-bom-002-bom-4", catalogSku: null, name: "Stator Winding Assembly 2HP", quantity: 1, uom: "each", unitCost: 120.00, isCustom: true },
        ],
      },
      {
        id: "li-bom-003",
        lineNumber: 3,
        rawText: '20x Centrifugal Pump Impeller 4" (PI-CEN-4)',
        parsedSku: "PI-CEN-4",
        parsedProductName: 'Centrifugal Pump Impeller 4"',
        parsedQuantity: 20,
        parsedUom: "units",
        parsedUnitPrice: 85.00,
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [{ catalogSku: "PI-CEN-4", catalogName: 'Centrifugal Pump Impeller 4"', catalogDescription: "4-inch cast iron centrifugal pump impeller, closed type.", catalogPrice: 85.00, catalogUom: "unit" }],
        issues: [],
        bomComponents: [
          { id: "li-bom-003-bom-0", catalogSku: null, name: 'Impeller Casting 4" CI', quantity: 1, uom: "each", unitCost: 55.00, isCustom: true },
          { id: "li-bom-003-bom-1", catalogSku: "LN-M10-50", name: "Lock Nut M10 50-Pack", quantity: 1, uom: "pack", unitCost: 5.60, isCustom: false },
          { id: "li-bom-003-bom-2", catalogSku: "FW-M10-100", name: "Flat Washer M10 100-Pack", quantity: 1, uom: "pack", unitCost: 3.90, isCustom: false },
        ],
      },
      {
        id: "li-bom-004",
        lineNumber: 4,
        rawText: '15x Gate Valve 3" Brass (GV-3-BR)',
        parsedSku: "GV-3-BR",
        parsedProductName: 'Gate Valve 3" Brass',
        parsedQuantity: 15,
        parsedUom: "units",
        parsedUnitPrice: 68.00,
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [{ catalogSku: "GV-3-BR", catalogName: 'Gate Valve 3" Brass', catalogDescription: "3-inch brass gate valve, 200 WOG rated.", catalogPrice: 68.00, catalogUom: "unit" }],
        issues: [],
        bomComponents: [
          { id: "li-bom-004-bom-0", catalogSku: "BF-3-SO", name: 'Brass Flange 3" Slip-On', quantity: 2, uom: "each", unitCost: 21.00, isCustom: false },
          { id: "li-bom-004-bom-1", catalogSku: "GK-FL-3", name: 'Flange Gasket Kit 3"', quantity: 1, uom: "set", unitCost: 3.50, isCustom: false },
          { id: "li-bom-004-bom-2", catalogSku: "PTFE-TAPE-12", name: "PTFE Thread Seal Tape 12-Roll", quantity: 1, uom: "pack", unitCost: 8.50, isCustom: false },
          { id: "li-bom-004-bom-3", catalogSku: null, name: "Gate Valve Body 3\" Brass Cast", quantity: 1, uom: "each", unitCost: 28.00, isCustom: true },
        ],
      },
    ],
    totalItems: 4,
    poNumber: null,
    dueDate: "2026-04-20",
    shipTo: "8800 Commerce Park Dr, Dock 2, Houston, TX 77036",
    shipVia: "FedEx Freight",
    paymentTerms: "Net 30",
    parseConfidence: 95,
    parseFieldConfidence: { partNumber: 98, qty: 97, price: 95, dueDate: 90, shipTo: 85 },
    parseMissingFields: [],
    mrpRoutedAt: null,
    ingestionSourceLabel: "email",
    drawings: [
      { id: "drw-001", fileName: "Pump-Station-Assembly-Drawing.pdf", revision: "Rev B", attachmentId: "att-bom-001", linkedLineItemIds: ["li-bom-001", "li-bom-002", "li-bom-003"] },
      { id: "drw-002", fileName: "Valve-Package-Specs.pdf", revision: "Rev A", attachmentId: "att-bom-002", linkedLineItemIds: ["li-bom-004"] },
    ],
    demoFlow: {
      scenario: "dynamic",
      stage: "rfq_received",
    },
  },
];
