import { Order } from "./types";

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    orderNumber: "ORD-2026-0047",
    status: "pending",
    createdAt: "2026-03-04T09:15:00Z",
    emailSubject: "Q1 Restock Order - Urgent",
    customer: {
      id: "cust-001",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-001",
        fileName: "order-items-handwritten.png",
        mimeType: "image/png",
        size: 2_150_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-001",
        lineNumber: 1,
        rawText: "50x Blue Widget 10pk  WDG-BLU-10",
        parsedSku: "WDG-BLU-10",
        parsedProductName: "Blue Widget 10-Pack",
        parsedQuantity: 50,
        parsedUom: "cases",
        parsedUnitPrice: 24.99,
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "WDG-BLU-10",
            catalogName: "Blue Widget 10-Pack",
            catalogDescription:
              "Premium blue widgets, 10 units per case. Industrial grade.",
            catalogPrice: 24.99,
            catalogUom: "case",
          },
        ],
        issues: [],
      },
      {
        id: "li-002",
        lineNumber: 2,
        rawText: "20 Red Gadgets",
        parsedSku: null,
        parsedProductName: "Red Gadget",
        parsedQuantity: 20,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 72,
        matchedCatalogItems: [
          {
            catalogSku: "GDG-RED-01",
            catalogName: "Red Gadget Standard",
            catalogDescription:
              "Standard red gadget, individual unit. Consumer grade.",
            catalogPrice: 12.5,
            catalogUom: "each",
          },
        ],
        issues: [
          "No SKU provided in source document",
          "Unit price not specified",
        ],
      },
      {
        id: "li-003",
        lineNumber: 3,
        rawText: "10 boxes Green Sprockets SPR-100",
        parsedSku: "SPR-100",
        parsedProductName: "Green Sprocket",
        parsedQuantity: 10,
        parsedUom: "boxes",
        parsedUnitPrice: 45.0,
        matchStatus: "conflict",
        confidence: 48,
        matchedCatalogItems: [
          {
            catalogSku: "SPR-100",
            catalogName: "Sprocket Standard (Silver)",
            catalogDescription:
              "Standard sprocket, silver finish. 25 units per box.",
            catalogPrice: 38.0,
            catalogUom: "box",
          },
          {
            catalogSku: "SPR-GRN-200",
            catalogName: "Green Sprocket Premium",
            catalogDescription:
              "Premium sprocket with green coating. 20 units per box.",
            catalogPrice: 52.0,
            catalogUom: "box",
          },
        ],
        issues: [
          'SKU "SPR-100" maps to "Sprocket Standard (Silver)" but handwritten name says "Green Sprocket"',
          "Possible match: SPR-GRN-200 Green Sprocket Premium",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-004",
        lineNumber: 4,
        rawText: "5 Flux Capacitors FLX-???",
        parsedSku: "FLX-???",
        parsedProductName: "Flux Capacitor",
        parsedQuantity: 5,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "SKU appears incomplete or illegible",
          "Verify item name with customer",
        ],
      },
      {
        id: "li-005",
        lineNumber: 5,
        rawText: "100 Copper Fasteners CF-250",
        parsedSku: "CF-250",
        parsedProductName: "Copper Fastener 250-Count",
        parsedQuantity: 100,
        parsedUom: "bags",
        parsedUnitPrice: 8.75,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "CF-250",
            catalogName: "Copper Fastener 250-Count Bag",
            catalogDescription:
              "High-quality copper fasteners, 250 per bag. Corrosion resistant.",
            catalogPrice: 8.75,
            catalogUom: "bag",
          },
        ],
        issues: [],
      },
      {
        id: "li-006",
        lineNumber: 6,
        rawText: "30 rubber seals",
        parsedSku: null,
        parsedProductName: "Rubber Seal",
        parsedQuantity: 30,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 65,
        matchedCatalogItems: [
          {
            catalogSku: "RS-STD-50",
            catalogName: "Rubber Seal Standard 50-Pack",
            catalogDescription: "Industrial rubber seals, 50 per pack.",
            catalogPrice: 15.0,
            catalogUom: "pack",
          },
          {
            catalogSku: "RS-HD-10",
            catalogName: "Rubber Seal Heavy Duty 10-Pack",
            catalogDescription:
              "Heavy duty rubber seals for high pressure, 10 per pack.",
            catalogPrice: 22.0,
            catalogUom: "pack",
          },
        ],
        issues: [
          "No SKU provided",
          "Multiple size variants exist - unable to determine exact product",
          "UOM unclear - could be individual units or packs",
        ],
      },
    ],
    totalItems: 6,
  },
  {
    id: "ord-002",
    orderNumber: "ORD-2026-0046",
    status: "fulfilled",
    createdAt: "2026-03-01T14:30:00Z",
    emailSubject: "February Replenishment Order",
    customer: {
      id: "cust-002",
      name: "Sarah Chen",
      email: "sarah.chen@meridianparts.com",
      phone: "(555) 876-5432",
      company: "Meridian Parts Co.",
      billingAddress: "340 Industrial Pkwy, Denver, CO 80201",
      shippingAddress: "340 Industrial Pkwy, Dock B, Denver, CO 80201",
    },
    attachments: [
      {
        id: "att-002",
        fileName: "feb-order-list.pdf",
        mimeType: "application/pdf",
        size: 890_000,
        url: "/sample-order.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-010",
        lineNumber: 1,
        rawText: "200x Steel Bolt M8 SB-M8-200",
        parsedSku: "SB-M8-200",
        parsedProductName: "Steel Bolt M8 200-Pack",
        parsedQuantity: 200,
        parsedUom: "packs",
        parsedUnitPrice: 14.5,
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "SB-M8-200",
            catalogName: "Steel Bolt M8 200-Pack",
            catalogDescription: "Grade 8 steel bolts, M8 thread, 200 per box.",
            catalogPrice: 14.5,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
      {
        id: "li-011",
        lineNumber: 2,
        rawText: "75 Nylon Washers NW-100",
        parsedSku: "NW-100",
        parsedProductName: "Nylon Washer 100-Pack",
        parsedQuantity: 75,
        parsedUom: "packs",
        parsedUnitPrice: 6.25,
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "NW-100",
            catalogName: "Nylon Washer 100-Count",
            catalogDescription: "Standard nylon washers, 100 per bag.",
            catalogPrice: 6.25,
            catalogUom: "bag",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 2,
  },
  {
    id: "ord-003",
    orderNumber: "ORD-2026-0045",
    status: "fulfilled",
    createdAt: "2026-02-25T11:00:00Z",
    emailSubject: "Re: Quarterly Supply Request",
    customer: {
      id: "cust-003",
      name: "Marcus Rivera",
      email: "m.rivera@toplinehardware.com",
      phone: "(555) 321-0987",
      company: "Topline Hardware LLC",
      billingAddress: "78 Main Street, Portland, OR 97201",
      shippingAddress: "900 Distribution Way, Portland, OR 97220",
    },
    attachments: [
      {
        id: "att-003",
        fileName: "supply-request-q1.png",
        mimeType: "image/png",
        size: 1_750_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-020",
        lineNumber: 1,
        rawText: "500 Brass Hinges BH-SM-500",
        parsedSku: "BH-SM-500",
        parsedProductName: "Brass Hinge Small 500-Pack",
        parsedQuantity: 500,
        parsedUom: "units",
        parsedUnitPrice: 0.85,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "BH-SM-500",
            catalogName: "Brass Hinge Small - Bulk 500",
            catalogDescription: "Small brass hinges for cabinet doors, bulk pack.",
            catalogPrice: 0.85,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-021",
        lineNumber: 2,
        rawText: "25 drawer slides",
        parsedSku: null,
        parsedProductName: "Drawer Slide",
        parsedQuantity: 25,
        parsedUom: "pairs",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 60,
        matchedCatalogItems: [
          {
            catalogSku: "DS-18-PR",
            catalogName: 'Drawer Slide 18" Pair',
            catalogDescription: '18-inch full extension drawer slides, sold in pairs.',
            catalogPrice: 11.0,
            catalogUom: "pair",
          },
          {
            catalogSku: "DS-22-PR",
            catalogName: 'Drawer Slide 22" Pair',
            catalogDescription: '22-inch full extension drawer slides, sold in pairs.',
            catalogPrice: 13.5,
            catalogUom: "pair",
          },
        ],
        issues: [
          "No SKU provided",
          "Size not specified - multiple lengths available (18\", 22\")",
        ],
      },
      {
        id: "li-022",
        lineNumber: 3,
        rawText: "40 cabinet knobs CK-RND",
        parsedSku: "CK-RND",
        parsedProductName: "Cabinet Knob Round",
        parsedQuantity: 40,
        parsedUom: "each",
        parsedUnitPrice: 3.25,
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "CK-RND",
            catalogName: "Cabinet Knob Round - Brushed Nickel",
            catalogDescription: "Round cabinet knob, brushed nickel finish.",
            catalogPrice: 3.25,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
  },
  {
    id: "ord-004",
    orderNumber: "ORD-2026-0044",
    status: "fulfilled",
    createdAt: "2026-02-18T08:45:00Z",
    emailSubject: "Monthly Auto-Parts Order",
    customer: {
      id: "cust-004",
      name: "Lisa Park",
      email: "lpark@velocityauto.com",
      phone: "(555) 654-3210",
      company: "Velocity Auto Supply",
      billingAddress: "2100 Motor Ave, Detroit, MI 48201",
      shippingAddress: "2100 Motor Ave, Bay 5, Detroit, MI 48201",
    },
    attachments: [
      {
        id: "att-004",
        fileName: "auto-parts-feb.pdf",
        mimeType: "application/pdf",
        size: 540_000,
        url: "/sample-order.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-030",
        lineNumber: 1,
        rawText: "150 Oil Filters OF-STD-10",
        parsedSku: "OF-STD-10",
        parsedProductName: "Oil Filter Standard 10-Pack",
        parsedQuantity: 150,
        parsedUom: "packs",
        parsedUnitPrice: 32.0,
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "OF-STD-10",
            catalogName: "Oil Filter Standard 10-Pack",
            catalogDescription: "Standard oil filter, fits most sedans. 10 per box.",
            catalogPrice: 32.0,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
      {
        id: "li-031",
        lineNumber: 2,
        rawText: "80 Brake Pads BP-CRM-4",
        parsedSku: "BP-CRM-4",
        parsedProductName: "Brake Pad Ceramic 4-Pack",
        parsedQuantity: 80,
        parsedUom: "sets",
        parsedUnitPrice: 28.5,
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "BP-CRM-4",
            catalogName: "Brake Pad Ceramic 4-Pack",
            catalogDescription: "Ceramic brake pads, low dust. Set of 4.",
            catalogPrice: 28.5,
            catalogUom: "set",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 2,
  },
  {
    id: "ord-005",
    orderNumber: "ORD-2026-0043",
    status: "fulfilled",
    createdAt: "2026-02-10T16:20:00Z",
    emailSubject: "Fwd: Plumbing supplies needed",
    customer: {
      id: "cust-005",
      name: "David Okonkwo",
      email: "david@plumbprosupply.com",
      phone: "(555) 789-0123",
      company: "PlumbPro Supply",
      billingAddress: "550 Pipeline Rd, Houston, TX 77001",
      shippingAddress: "550 Pipeline Rd, Warehouse C, Houston, TX 77001",
    },
    attachments: [
      {
        id: "att-005",
        fileName: "plumbing-list.png",
        mimeType: "image/png",
        size: 1_200_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-040",
        lineNumber: 1,
        rawText: "300 PVC Elbows 90deg PE-90-300",
        parsedSku: "PE-90-300",
        parsedProductName: "PVC Elbow 90-Degree Bulk 300",
        parsedQuantity: 300,
        parsedUom: "units",
        parsedUnitPrice: 0.45,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "PE-90-300",
            catalogName: "PVC Elbow 90° - 300 Pack",
            catalogDescription: '3/4" PVC 90-degree elbow fittings, 300 per case.',
            catalogPrice: 0.45,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-041",
        lineNumber: 2,
        rawText: "50 copper tees 1/2",
        parsedSku: null,
        parsedProductName: 'Copper Tee 1/2"',
        parsedQuantity: 50,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "confirmed",
        confidence: 91,
        matchedCatalogItems: [
          {
            catalogSku: "CT-HALF",
            catalogName: 'Copper Tee 1/2" Fitting',
            catalogDescription: '1/2-inch copper tee fitting for residential plumbing.',
            catalogPrice: 2.1,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 2,
  },
];
