import { Order } from "./types";

export const mockOrders: Order[] = [
  {
    id: "ord-demo-004",
    orderNumber: "ORD-2026-0051",
    status: "pending",
    source: "email",
    createdAt: "2026-03-13T09:35:00Z",
    emailSubject: "PO-2026-0342 — Updated quantities (please expedite)",
    customer: {
      id: "cust-demo-001",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-demo-004",
        fileName: "PO-2026-0342-mismatch.pdf",
        mimeType: "application/pdf",
        size: 178_000,
        url: "/po-mismatch-q-2026-0047.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-041",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 @ 44.90 due 2026-03-28 rev D",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 44.9,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 44.9,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-042",
        lineNumber: 2,
        rawText: "90 Pump Impeller 4in IMP-4-220 @ 78.00 due 2026-03-29 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 90,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-043",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 @ 12.40 due 2026-03-22 rev A",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        requestedDueDate: "2026-03-22",
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp",
            catalogDescription: "High temperature seal kit.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    poNumber: "PO-2026-0342",
    dueDate: "2026-03-22",
    parseConfidence: 98,
    ingestionSourceLabel: "Outlook - PO PDF",
    demoFlow: {
      scenario: "po_mismatch",
      stage: "po_validated",
      quoteNumber: "Q-2026-0047",
      poNumber: "PO-2026-0342",
      quoteComparison: {
        overallMatch: false,
        checks: [
          {
            field: "price",
            matches: false,
            quoteValue: "VB-316-90 = $42.50",
            incomingValue: "VB-316-90 = $44.90",
            note: "Price increased vs quoted amount",
          },
          {
            field: "quantity",
            matches: false,
            quoteValue: "IMP-4-220 = 60",
            incomingValue: "IMP-4-220 = 90",
            note: "Quantity increased vs quote",
          },
          {
            field: "dueDate",
            matches: false,
            quoteValue: "SK-HT-55 = 2026-03-30",
            incomingValue: "SK-HT-55 = 2026-03-22",
            note: "Due date pulled in by 8 days",
          },
          {
            field: "drawingRev",
            matches: false,
            quoteValue: "VB-316-90 Rev C",
            incomingValue: "VB-316-90 Rev D",
            note: "Drawing rev changed",
          },
        ],
      },
      correctionDraftEmail: {
        to: "james.whitfield@acmedist.com",
        subject: "PO-2026-0342 needs correction to match Quote Q-2026-0047",
        body: "Hi James,\n\nThanks for sending PO-2026-0342. We detected differences against Quote Q-2026-0047:\n- Price: VB-316-90 is $44.90 on PO vs $42.50 quoted\n- Quantity: IMP-4-220 is 90 on PO vs 60 quoted\n- Due date: SK-HT-55 is 2026-03-22 on PO vs 2026-03-30 quoted\n- Drawing rev: VB-316-90 is Rev D on PO vs Rev C quoted\n\nPlease send a corrected PO or confirm that you want us to requote these lines.\n\nBest,\nHexa Sales Ops",
      },
      erpSync: {
        state: "blocked",
        timeline: [
          {
            label: "PO parsed from email attachment",
            state: "queued",
            at: "2026-03-13T09:35:42Z",
          },
          {
            label: "Quote comparison check failed",
            state: "blocked",
            at: "2026-03-13T09:36:14Z",
          },
        ],
      },
    },
  },
  {
    id: "ord-demo-003",
    orderNumber: "ORD-2026-0050",
    status: "fulfilled",
    source: "email",
    createdAt: "2026-03-13T09:20:00Z",
    emailSubject: "PO-2026-0341 — Confirmed against Quote Q-2026-0047",
    customer: {
      id: "cust-demo-001",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-demo-003",
        fileName: "PO-2026-0341-match.pdf",
        mimeType: "application/pdf",
        size: 165_000,
        url: "/po-match-q-2026-0047.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-031",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 @ 42.50 due 2026-03-28 rev C",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 42.5,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 42.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-032",
        lineNumber: 2,
        rawText: "60 Pump Impeller 4in IMP-4-220 @ 78.00 due 2026-03-29 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 60,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-033",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 @ 12.40 due 2026-03-30 rev A",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        requestedDueDate: "2026-03-30",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp",
            catalogDescription: "High temperature seal kit.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    poNumber: "PO-2026-0341",
    dueDate: "2026-03-30",
    parseConfidence: 99,
    ingestionSourceLabel: "Outlook - PO PDF",
    mrpRoutingStatus: "pushed_to_mrp",
    mrpRoutedAt: "2026-03-13T09:23:07Z",
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0047",
      poNumber: "PO-2026-0341",
      quoteComparison: {
        overallMatch: true,
        checks: [
          {
            field: "price",
            matches: true,
            quoteValue: "All lines matched quoted prices",
            incomingValue: "All lines matched quoted prices",
          },
          {
            field: "quantity",
            matches: true,
            quoteValue: "All line quantities unchanged",
            incomingValue: "All line quantities unchanged",
          },
          {
            field: "dueDate",
            matches: true,
            quoteValue: "Due dates aligned with quote",
            incomingValue: "Due dates aligned with quote",
          },
          {
            field: "drawingRev",
            matches: true,
            quoteValue: "All lines at approved revisions",
            incomingValue: "All lines at approved revisions",
          },
        ],
      },
      erpSync: {
        state: "acknowledged",
        timeline: [
          {
            label: "PO parsed from email attachment",
            state: "queued",
            at: "2026-03-13T09:20:12Z",
          },
          {
            label: "PO matched against quote Q-2026-0047",
            state: "sent",
            at: "2026-03-13T09:21:04Z",
          },
          {
            label: "ERP order acknowledged",
            state: "acknowledged",
            at: "2026-03-13T09:23:07Z",
          },
        ],
      },
    },
  },
  {
    id: "ord-demo-002",
    orderNumber: "ORD-2026-0049",
    status: "pending",
    source: "email",
    createdAt: "2026-03-13T08:55:00Z",
    emailSubject: "Quick RFQ — handwritten shop-floor request",
    customer: {
      id: "cust-demo-002",
      name: "Ravi Patel",
      email: "ravi.patel@summitfab.com",
      phone: "(555) 778-4010",
      company: "Summit Fabrication",
      billingAddress: "22 Foundry Lane, Pittsburgh, PA 15201",
      shippingAddress: "22 Foundry Lane, Dock 2, Pittsburgh, PA 15201",
    },
    attachments: [
      {
        id: "att-demo-002",
        fileName: "RFQ-handwritten-note.pdf",
        mimeType: "application/pdf",
        size: 145_000,
        url: "/rfq-handwritten-note.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-021",
        lineNumber: 1,
        rawText: "30 shaft collars SC-12 rev B",
        parsedSku: "SC-12",
        parsedProductName: "Shaft Collar 12mm",
        parsedQuantity: 30,
        parsedUom: "units",
        parsedUnitPrice: 6.9,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 93,
        matchedCatalogItems: [
          {
            catalogSku: "SC-12",
            catalogName: "Shaft Collar 12mm",
            catalogDescription: "Steel shaft collar, 12mm ID.",
            catalogPrice: 6.9,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-022",
        lineNumber: 2,
        rawText: "75 bearings BB-6205 rev C",
        parsedSku: "BB-6205",
        parsedProductName: "Deep Groove Bearing 6205",
        parsedQuantity: 75,
        parsedUom: "units",
        parsedUnitPrice: 4.8,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "BB-6205",
            catalogName: "Deep Groove Bearing 6205-2RS",
            catalogDescription: "Sealed bearing, both sides.",
            catalogPrice: 4.8,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-023",
        lineNumber: 3,
        rawText: "20 gasket packs GK-STD-25",
        parsedSku: "GK-STD-25",
        parsedProductName: "Standard Gasket Pack",
        parsedQuantity: 20,
        parsedUom: "packs",
        parsedUnitPrice: 11.5,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "GK-STD-25",
            catalogName: "Standard Gasket Pack",
            catalogDescription: "General purpose gasket set.",
            catalogPrice: 11.5,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 94,
    ingestionSourceLabel: "Outlook - Handwritten RFQ",
    demoFlow: {
      scenario: "rfq_handwritten",
      stage: "quote_prepared",
      quoteNumber: "Q-2026-0048",
    },
  },
  {
    id: "ord-demo-001",
    orderNumber: "ORD-2026-0048",
    status: "pending",
    source: "email",
    createdAt: "2026-03-13T08:40:00Z",
    emailSubject: "RFQ-2026-1187 — Need quote for March machining lot (CSV)",
    customer: {
      id: "cust-demo-003",
      name: "Elena Marsh",
      email: "elena.marsh@northfieldcomponents.com",
      phone: "(555) 220-1178",
      company: "Northfield Components",
      billingAddress: "810 Industrial Parkway, Dayton, OH 45402",
      shippingAddress: "810 Industrial Parkway, Gate 6, Dayton, OH 45402",
    },
    attachments: [
      {
        id: "att-demo-001",
        fileName: "RFQ-2026-1187-Northfield.csv",
        mimeType: "text/csv",
        size: 34_500,
        url: "/rfq-request-march.csv",
      },
    ],
    lineItems: [
      {
        id: "li-demo-011",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 rev C",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 42.5,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 42.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-012",
        lineNumber: 2,
        rawText: "60 Pump Impeller 4in IMP-4-220 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 60,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-013",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 rev A",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        requestedDueDate: "2026-03-30",
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp",
            catalogDescription: "High temperature seal kit.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 97,
    ingestionSourceLabel: "Outlook - RFQ CSV",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "quote_prepared",
      quoteNumber: "Q-2026-0047",
    },
  },
  {
    id: "ord-001",
    orderNumber: "ORD-2026-0047",
    status: "pending",
    source: "email",
    createdAt: "2026-03-04T09:15:00Z",
    emailSubject: "Q1 Restock Order - Urgent",
    customer: {
      id: "cust-001",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-001",
        fileName: "order-items-handwritten.png",
        mimeType: "image/png",
        size: 2_150_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-001",
        lineNumber: 1,
        rawText: "50x Blue Widget 10pk  WDG-BLU-10",
        parsedSku: "WDG-BLU-10",
        parsedProductName: "Blue Widget 10-Pack",
        parsedQuantity: 50,
        parsedUom: "cases",
        parsedUnitPrice: 24.99,
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "WDG-BLU-10",
            catalogName: "Blue Widget 10-Pack",
            catalogDescription:
              "Premium blue widgets, 10 units per case. Industrial grade.",
            catalogPrice: 24.99,
            catalogUom: "case",
          },
        ],
        issues: [],
      },
      {
        id: "li-002",
        lineNumber: 2,
        rawText: "20 Red Gadgets",
        parsedSku: null,
        parsedProductName: "Red Gadget",
        parsedQuantity: 20,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 72,
        matchedCatalogItems: [
          {
            catalogSku: "GDG-RED-01",
            catalogName: "Red Gadget Standard",
            catalogDescription:
              "Standard red gadget, individual unit. Consumer grade.",
            catalogPrice: 12.5,
            catalogUom: "each",
          },
        ],
        issues: [
          "No SKU provided in source document",
          "Unit price not specified",
        ],
      },
      {
        id: "li-003",
        lineNumber: 3,
        rawText: "10 boxes Green Sprockets SPR-100",
        parsedSku: "SPR-100",
        parsedProductName: "Green Sprocket",
        parsedQuantity: 10,
        parsedUom: "boxes",
        parsedUnitPrice: 45.0,
        matchStatus: "conflict",
        confidence: 48,
        matchedCatalogItems: [
          {
            catalogSku: "SPR-100",
            catalogName: "Sprocket Standard (Silver)",
            catalogDescription:
              "Standard sprocket, silver finish. 25 units per box.",
            catalogPrice: 38.0,
            catalogUom: "box",
          },
          {
            catalogSku: "SPR-GRN-200",
            catalogName: "Green Sprocket Premium",
            catalogDescription:
              "Premium sprocket with green coating. 20 units per box.",
            catalogPrice: 52.0,
            catalogUom: "box",
          },
        ],
        issues: [
          'SKU "SPR-100" maps to "Sprocket Standard (Silver)" but handwritten name says "Green Sprocket"',
          "Possible match: SPR-GRN-200 Green Sprocket Premium",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-004",
        lineNumber: 4,
        rawText: "5 Flux Capacitors FLX-???",
        parsedSku: "FLX-???",
        parsedProductName: "Flux Capacitor",
        parsedQuantity: 5,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "SKU appears incomplete or illegible",
          "Verify item name with customer",
        ],
      },
      {
        id: "li-005",
        lineNumber: 5,
        rawText: "100 Copper Fasteners CF-250",
        parsedSku: "CF-250",
        parsedProductName: "Copper Fastener 250-Count",
        parsedQuantity: 100,
        parsedUom: "bags",
        parsedUnitPrice: 8.75,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "CF-250",
            catalogName: "Copper Fastener 250-Count Bag",
            catalogDescription:
              "High-quality copper fasteners, 250 per bag. Corrosion resistant.",
            catalogPrice: 8.75,
            catalogUom: "bag",
          },
        ],
        issues: [],
      },
      {
        id: "li-006",
        lineNumber: 6,
        rawText: "30 rubber seals",
        parsedSku: null,
        parsedProductName: "Rubber Seal",
        parsedQuantity: 30,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 65,
        matchedCatalogItems: [
          {
            catalogSku: "RS-STD-50",
            catalogName: "Rubber Seal Standard 50-Pack",
            catalogDescription: "Industrial rubber seals, 50 per pack.",
            catalogPrice: 15.0,
            catalogUom: "pack",
          },
          {
            catalogSku: "RS-HD-10",
            catalogName: "Rubber Seal Heavy Duty 10-Pack",
            catalogDescription:
              "Heavy duty rubber seals for high pressure, 10 per pack.",
            catalogPrice: 22.0,
            catalogUom: "pack",
          },
        ],
        issues: [
          "No SKU provided",
          "Multiple size variants exist - unable to determine exact product",
          "UOM unclear - could be individual units or packs",
        ],
      },
    ],
    totalItems: 6,
    poNumber: "PO-2026-0341",
    dueDate: "21 Mar 2026",
    shipTo: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    shipVia: "Standard Freight",
    paymentTerms: "Net 30",
    parseConfidence: 91,
    parseFieldConfidence: {
      partNumber: 92,
      price: 88,
      qty: 96,
      dueDate: 90,
      shipTo: 90,
      shipVia: 86,
      paymentTerms: 86,
    },
    parseMissingFields: [],
    mrpRoutingStatus: "pushed_to_mrp",
    mrpRoutedAt: "2026-03-04T09:16:00Z",
    ingestionSourceLabel: "taskpane:email",
  },
  {
    id: "ord-002",
    orderNumber: "ORD-2026-0046",
    status: "fulfilled",
    source: "ecommerce",
    createdAt: "2026-03-01T14:30:00Z",
    emailSubject: "February Replenishment Order",
    customer: {
      id: "cust-002",
      name: "Sarah Chen",
      email: "sarah.chen@meridianparts.com",
      phone: "(555) 876-5432",
      company: "Meridian Parts Co.",
      billingAddress: "340 Industrial Pkwy, Denver, CO 80201",
      shippingAddress: "340 Industrial Pkwy, Dock B, Denver, CO 80201",
    },
    attachments: [
      {
        id: "att-002",
        fileName: "feb-order-list.pdf",
        mimeType: "application/pdf",
        size: 890_000,
        url: "/sample-order.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-010",
        lineNumber: 1,
        rawText: "200x Steel Bolt M8 SB-M8-200",
        parsedSku: "SB-M8-200",
        parsedProductName: "Steel Bolt M8 200-Pack",
        parsedQuantity: 200,
        parsedUom: "packs",
        parsedUnitPrice: 14.5,
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "SB-M8-200",
            catalogName: "Steel Bolt M8 200-Pack",
            catalogDescription: "Grade 8 steel bolts, M8 thread, 200 per box.",
            catalogPrice: 14.5,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
      {
        id: "li-011",
        lineNumber: 2,
        rawText: "75 Nylon Washers NW-100",
        parsedSku: "NW-100",
        parsedProductName: "Nylon Washer 100-Pack",
        parsedQuantity: 75,
        parsedUom: "packs",
        parsedUnitPrice: 6.25,
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "NW-100",
            catalogName: "Nylon Washer 100-Count",
            catalogDescription: "Standard nylon washers, 100 per bag.",
            catalogPrice: 6.25,
            catalogUom: "bag",
          },
        ],
        issues: [],
      },
      {
        id: "li-012",
        lineNumber: 3,
        rawText: "50 Lock Washers LW-M8 or LW-M10",
        parsedSku: "LW-M8",
        parsedProductName: "Lock Washer",
        parsedQuantity: 50,
        parsedUom: "packs",
        parsedUnitPrice: 4.5,
        matchStatus: "conflict",
        confidence: 45,
        matchedCatalogItems: [
          {
            catalogSku: "LW-M8",
            catalogName: "Lock Washer M8 50-Pack",
            catalogDescription: "Split lock washers, M8 size. 50 per pack.",
            catalogPrice: 3.75,
            catalogUom: "pack",
          },
          {
            catalogSku: "LW-M10",
            catalogName: "Lock Washer M10 50-Pack",
            catalogDescription: "Split lock washers, M10 size. 50 per pack.",
            catalogPrice: 4.95,
            catalogUom: "pack",
          },
        ],
        issues: [
          'Source mentions both "LW-M8" and "LW-M10" — unclear which size is needed',
          "Price differs between options ($3.75 vs $4.95)",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-013",
        lineNumber: 4,
        rawText: "30 titanium rivets ???",
        parsedSku: null,
        parsedProductName: "Titanium Rivet",
        parsedQuantity: 30,
        parsedUom: "bags",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "SKU missing from source document",
          "Rivet size and head type not specified",
        ],
      },
    ],
    totalItems: 4,
    poNumber: "PO-2026-0318",
    dueDate: "28 Feb 2026",
    shipTo: "340 Industrial Pkwy, Dock B, Denver, CO 80201",
    shipVia: "UPS Ground",
    paymentTerms: "Net 15",
    parseConfidence: 84,
    parseFieldConfidence: {
      partNumber: 90,
      price: 92,
      qty: 96,
      dueDate: 84,
      shipTo: 90,
      shipVia: 78,
      paymentTerms: 80,
    },
    parseMissingFields: ["shipVia"],
    mrpRoutingStatus: "staged_for_review",
    mrpRoutedAt: null,
    ingestionSourceLabel: "storefront:upload",
  },
  {
    id: "ord-003",
    orderNumber: "ORD-2026-0045",
    status: "fulfilled",
    source: "email",
    createdAt: "2026-02-25T11:00:00Z",
    emailSubject: "Re: Quarterly Supply Request",
    customer: {
      id: "cust-003",
      name: "Marcus Rivera",
      email: "m.rivera@toplinehardware.com",
      phone: "(555) 321-0987",
      company: "Topline Hardware LLC",
      billingAddress: "78 Main Street, Portland, OR 97201",
      shippingAddress: "900 Distribution Way, Portland, OR 97220",
    },
    attachments: [
      {
        id: "att-003",
        fileName: "supply-request-q1.png",
        mimeType: "image/png",
        size: 1_750_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-020",
        lineNumber: 1,
        rawText: "500 Brass Hinges BH-SM-500",
        parsedSku: "BH-SM-500",
        parsedProductName: "Brass Hinge Small 500-Pack",
        parsedQuantity: 500,
        parsedUom: "units",
        parsedUnitPrice: 0.85,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "BH-SM-500",
            catalogName: "Brass Hinge Small - Bulk 500",
            catalogDescription: "Small brass hinges for cabinet doors, bulk pack.",
            catalogPrice: 0.85,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-021",
        lineNumber: 2,
        rawText: "25 drawer slides",
        parsedSku: null,
        parsedProductName: "Drawer Slide",
        parsedQuantity: 25,
        parsedUom: "pairs",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 60,
        matchedCatalogItems: [
          {
            catalogSku: "DS-18-PR",
            catalogName: 'Drawer Slide 18" Pair',
            catalogDescription: '18-inch full extension drawer slides, sold in pairs.',
            catalogPrice: 11.0,
            catalogUom: "pair",
          },
          {
            catalogSku: "DS-22-PR",
            catalogName: 'Drawer Slide 22" Pair',
            catalogDescription: '22-inch full extension drawer slides, sold in pairs.',
            catalogPrice: 13.5,
            catalogUom: "pair",
          },
        ],
        issues: [
          "No SKU provided",
          "Size not specified - multiple lengths available (18\", 22\")",
        ],
      },
      {
        id: "li-022",
        lineNumber: 3,
        rawText: "40 cabinet knobs CK-RND",
        parsedSku: "CK-RND",
        parsedProductName: "Cabinet Knob Round",
        parsedQuantity: 40,
        parsedUom: "each",
        parsedUnitPrice: 3.25,
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "CK-RND",
            catalogName: "Cabinet Knob Round - Brushed Nickel",
            catalogDescription: "Round cabinet knob, brushed nickel finish.",
            catalogPrice: 3.25,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
      {
        id: "li-023",
        lineNumber: 4,
        rawText: "60 soft-close hinges SC-35 or SC-40",
        parsedSku: "SC-35",
        parsedProductName: "Soft-Close Hinge",
        parsedQuantity: 60,
        parsedUom: "each",
        parsedUnitPrice: 5.5,
        matchStatus: "conflict",
        confidence: 50,
        matchedCatalogItems: [
          {
            catalogSku: "SC-35",
            catalogName: "Soft-Close Hinge 35mm Cup",
            catalogDescription: "35mm cup soft-close cabinet hinge, 110° opening.",
            catalogPrice: 4.75,
            catalogUom: "each",
          },
          {
            catalogSku: "SC-40",
            catalogName: "Soft-Close Hinge 40mm Cup",
            catalogDescription: "40mm cup soft-close cabinet hinge, 110° opening.",
            catalogPrice: 6.25,
            catalogUom: "each",
          },
        ],
        issues: [
          'Source mentions both "SC-35" and "SC-40" — cup size unclear',
          "Price differs between options ($4.75 vs $6.25)",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-024",
        lineNumber: 5,
        rawText: "15 lazy susan bearings ???",
        parsedSku: null,
        parsedProductName: "Lazy Susan Bearing",
        parsedQuantity: 15,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "Bearing diameter not specified",
          "Verify item details with customer",
        ],
      },
    ],
    totalItems: 5,
    poNumber: "PO-2026-0299",
    dueDate: "12 Mar 2026",
    shipTo: "900 Distribution Way, Portland, OR 97220",
    shipVia: "FedEx Economy",
    paymentTerms: "Net 30",
    parseConfidence: 89,
    parseFieldConfidence: {
      partNumber: 88,
      price: 85,
      qty: 96,
      dueDate: 88,
      shipTo: 92,
      shipVia: 84,
      paymentTerms: 90,
    },
    parseMissingFields: [],
    mrpRoutingStatus: "pushed_to_mrp",
    mrpRoutedAt: "2026-02-25T11:01:00Z",
    ingestionSourceLabel: "email:attachment",
  },
  {
    id: "ord-004",
    orderNumber: "ORD-2026-0044",
    status: "fulfilled",
    source: "phone",
    createdAt: "2026-02-18T08:45:00Z",
    emailSubject: "Monthly Auto-Parts Order",
    customer: {
      id: "cust-004",
      name: "Lisa Park",
      email: "lpark@velocityauto.com",
      phone: "(555) 654-3210",
      company: "Velocity Auto Supply",
      billingAddress: "2100 Motor Ave, Detroit, MI 48201",
      shippingAddress: "2100 Motor Ave, Bay 5, Detroit, MI 48201",
    },
    attachments: [
      {
        id: "att-004",
        fileName: "auto-parts-feb.pdf",
        mimeType: "application/pdf",
        size: 540_000,
        url: "/sample-order.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-030",
        lineNumber: 1,
        rawText: "150 Oil Filters OF-STD-10",
        parsedSku: "OF-STD-10",
        parsedProductName: "Oil Filter Standard 10-Pack",
        parsedQuantity: 150,
        parsedUom: "packs",
        parsedUnitPrice: 32.0,
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "OF-STD-10",
            catalogName: "Oil Filter Standard 10-Pack",
            catalogDescription: "Standard oil filter, fits most sedans. 10 per box.",
            catalogPrice: 32.0,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
      {
        id: "li-031",
        lineNumber: 2,
        rawText: "80 Brake Pads BP-CRM-4",
        parsedSku: "BP-CRM-4",
        parsedProductName: "Brake Pad Ceramic 4-Pack",
        parsedQuantity: 80,
        parsedUom: "sets",
        parsedUnitPrice: 28.5,
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "BP-CRM-4",
            catalogName: "Brake Pad Ceramic 4-Pack",
            catalogDescription: "Ceramic brake pads, low dust. Set of 4.",
            catalogPrice: 28.5,
            catalogUom: "set",
          },
        ],
        issues: [],
      },
      {
        id: "li-032",
        lineNumber: 3,
        rawText: "40 Spark Plugs SP-IR7 or SP-PT4",
        parsedSku: "SP-IR7",
        parsedProductName: "Spark Plug",
        parsedQuantity: 40,
        parsedUom: "boxes",
        parsedUnitPrice: 9.0,
        matchStatus: "conflict",
        confidence: 44,
        matchedCatalogItems: [
          {
            catalogSku: "SP-IR7",
            catalogName: "Spark Plug Iridium 4-Pack",
            catalogDescription: "Iridium spark plugs, long-life. 4 per box.",
            catalogPrice: 11.5,
            catalogUom: "box",
          },
          {
            catalogSku: "SP-PT4",
            catalogName: "Spark Plug Platinum 4-Pack",
            catalogDescription: "Platinum spark plugs, standard performance. 4 per box.",
            catalogPrice: 7.25,
            catalogUom: "box",
          },
        ],
        issues: [
          'Source mentions both "SP-IR7" and "SP-PT4" — unclear which type is needed',
          "Price differs significantly ($11.50 iridium vs $7.25 platinum)",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-033",
        lineNumber: 4,
        rawText: "25 cabin air filters ???",
        parsedSku: null,
        parsedProductName: "Cabin Air Filter",
        parsedQuantity: 25,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "Vehicle make/model not specified",
          "Filter dimensions unknown — unable to match",
        ],
      },
    ],
    totalItems: 4,
    poNumber: "PO-2026-0253",
    dueDate: "01 Mar 2026",
    shipTo: "2100 Motor Ave, Bay 5, Detroit, MI 48201",
    shipVia: "DHL Express",
    paymentTerms: "Net 30",
    parseConfidence: 87,
    parseFieldConfidence: {
      partNumber: 90,
      price: 90,
      qty: 96,
      dueDate: 86,
      shipTo: 90,
      shipVia: 82,
      paymentTerms: 86,
    },
    parseMissingFields: [],
    mrpRoutingStatus: "pushed_to_mrp",
    mrpRoutedAt: "2026-02-18T08:46:00Z",
    ingestionSourceLabel: "calls:simulated",
  },
  {
    id: "ord-005",
    orderNumber: "ORD-2026-0043",
    status: "fulfilled",
    source: "ecommerce",
    createdAt: "2026-02-10T16:20:00Z",
    emailSubject: "Fwd: Plumbing supplies needed",
    customer: {
      id: "cust-005",
      name: "David Okonkwo",
      email: "david@plumbprosupply.com",
      phone: "(555) 789-0123",
      company: "PlumbPro Supply",
      billingAddress: "550 Pipeline Rd, Houston, TX 77001",
      shippingAddress: "550 Pipeline Rd, Warehouse C, Houston, TX 77001",
    },
    attachments: [
      {
        id: "att-005",
        fileName: "plumbing-list.png",
        mimeType: "image/png",
        size: 1_200_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-040",
        lineNumber: 1,
        rawText: "300 PVC Elbows 90deg PE-90-300",
        parsedSku: "PE-90-300",
        parsedProductName: "PVC Elbow 90-Degree Bulk 300",
        parsedQuantity: 300,
        parsedUom: "units",
        parsedUnitPrice: 0.45,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "PE-90-300",
            catalogName: "PVC Elbow 90° - 300 Pack",
            catalogDescription: '3/4" PVC 90-degree elbow fittings, 300 per case.',
            catalogPrice: 0.45,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-041",
        lineNumber: 2,
        rawText: "50 copper tees 1/2",
        parsedSku: null,
        parsedProductName: 'Copper Tee 1/2"',
        parsedQuantity: 50,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "confirmed",
        confidence: 91,
        matchedCatalogItems: [
          {
            catalogSku: "CT-HALF",
            catalogName: 'Copper Tee 1/2" Fitting',
            catalogDescription: '1/2-inch copper tee fitting for residential plumbing.',
            catalogPrice: 2.1,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
      {
        id: "li-042",
        lineNumber: 3,
        rawText: "20 ball valves BV-075 or BV-100",
        parsedSku: "BV-075",
        parsedProductName: "Ball Valve",
        parsedQuantity: 20,
        parsedUom: "each",
        parsedUnitPrice: 18.0,
        matchStatus: "conflict",
        confidence: 46,
        matchedCatalogItems: [
          {
            catalogSku: "BV-075",
            catalogName: 'Ball Valve 3/4" Brass',
            catalogDescription: '3/4-inch brass ball valve, full port. Residential grade.',
            catalogPrice: 14.5,
            catalogUom: "each",
          },
          {
            catalogSku: "BV-100",
            catalogName: 'Ball Valve 1" Brass',
            catalogDescription: '1-inch brass ball valve, full port. Commercial grade.',
            catalogPrice: 22.0,
            catalogUom: "each",
          },
        ],
        issues: [
          'Source mentions both "BV-075" and "BV-100" — pipe size unclear',
          "Price differs between options ($14.50 vs $22.00)",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-043",
        lineNumber: 4,
        rawText: "100 pipe hangers assorted",
        parsedSku: null,
        parsedProductName: "Pipe Hanger Assorted",
        parsedQuantity: 100,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "Pipe size and hanger type not specified",
          "\"Assorted\" is too vague to match to a specific SKU",
        ],
      },
    ],
    totalItems: 4,
    poNumber: "PO-2026-0208",
    dueDate: "22 Feb 2026",
    shipTo: "550 Pipeline Rd, Warehouse C, Houston, TX 77001",
    shipVia: "ShipStation",
    paymentTerms: "Net 45",
    parseConfidence: 83,
    parseFieldConfidence: {
      partNumber: 84,
      price: 82,
      qty: 95,
      dueDate: 84,
      shipTo: 92,
      shipVia: 80,
      paymentTerms: 84,
    },
    parseMissingFields: ["price"],
    mrpRoutingStatus: "staged_for_review",
    mrpRoutedAt: null,
    ingestionSourceLabel: "storefront:type",
  },
];
