import { Order } from "./types";

export const mockOrders: Order[] = [
  // 1. RFQ Received — interactive demo entry point
  {
    id: "ord-demo-005",
    orderNumber: "ORD-2026-0052",
    stage: "rfq_received",
    source: "email",
    createdAt: "2026-03-13T10:05:00Z",
    emailSubject: "RFQ — CNC machining parts for Q2 production run",
    customer: {
      id: "cust-demo-005",
      name: "Tom Wagner",
      email: "tom.wagner@pacificindustrial.com",
      phone: "(555) 401-8833",
      company: "Pacific Industrial Co.",
      billingAddress: "4200 Harbor Blvd, Suite 100, Long Beach, CA 90802",
      shippingAddress: "4200 Harbor Blvd, Dock 3, Long Beach, CA 90802",
    },
    attachments: [
      {
        id: "att-demo-005",
        fileName: "RFQ-Pacific-Q2-2026.pdf",
        mimeType: "application/pdf",
        size: 3_560,
        url: "/rfq-pacific-q2-2026.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-051",
        lineNumber: 1,
        rawText: "200 Aluminum Bracket AL-BRK-100",
        parsedSku: "AL-BRK-100",
        parsedProductName: "Aluminum Bracket 100mm",
        parsedQuantity: 200,
        parsedUom: "units",
        parsedUnitPrice: 8.75,
        requestedDueDate: "2026-04-15",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "AL-BRK-100",
            catalogName: "Aluminum Bracket 100mm",
            catalogDescription: "CNC machined aluminum bracket, 100mm span.",
            catalogPrice: 8.75,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-052",
        lineNumber: 2,
        rawText: "50 stainless dowel pins",
        parsedSku: null,
        parsedProductName: "Stainless Dowel Pin",
        parsedQuantity: 50,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 62,
        matchedCatalogItems: [
          {
            catalogSku: "DP-SS-6",
            catalogName: "Stainless Dowel Pin 6mm",
            catalogDescription: "303 stainless dowel pin, 6mm diameter.",
            catalogPrice: 1.2,
            catalogUom: "unit",
          },
          {
            catalogSku: "DP-SS-8",
            catalogName: "Stainless Dowel Pin 8mm",
            catalogDescription: "303 stainless dowel pin, 8mm diameter.",
            catalogPrice: 1.45,
            catalogUom: "unit",
          },
        ],
        issues: [
          "No SKU provided — diameter not specified",
          "Multiple sizes available (6mm, 8mm)",
        ],
      },
      {
        id: "li-demo-053",
        lineNumber: 3,
        rawText: "30 Titanium Shaft Collar TC-25 or TC-30",
        parsedSku: "TC-25",
        parsedProductName: "Titanium Shaft Collar",
        parsedQuantity: 30,
        parsedUom: "units",
        parsedUnitPrice: 22.0,
        matchStatus: "conflict",
        confidence: 48,
        matchedCatalogItems: [
          {
            catalogSku: "TC-25",
            catalogName: "Titanium Shaft Collar 25mm",
            catalogDescription: "Grade 5 titanium collar, 25mm ID.",
            catalogPrice: 18.5,
            catalogUom: "unit",
          },
          {
            catalogSku: "TC-30",
            catalogName: "Titanium Shaft Collar 30mm",
            catalogDescription: "Grade 5 titanium collar, 30mm ID.",
            catalogPrice: 24.0,
            catalogUom: "unit",
          },
        ],
        issues: [
          "Source mentions both TC-25 and TC-30 — bore size unclear",
          "Price differs between options ($18.50 vs $24.00)",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-demo-054",
        lineNumber: 4,
        rawText: "100 custom spacers ???",
        parsedSku: null,
        parsedProductName: "Custom Spacer",
        parsedQuantity: 100,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "Material and dimensions not specified",
          "\"Custom\" suggests a non-standard part — verify with customer",
        ],
      },
      {
        id: "li-demo-055",
        lineNumber: 5,
        rawText: "80 Precision Bushing PB-440 rev B",
        parsedSku: "PB-440",
        parsedProductName: "Precision Bushing",
        parsedQuantity: 80,
        parsedUom: "units",
        parsedUnitPrice: 6.5,
        requestedDueDate: "2026-04-20",
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "PB-440",
            catalogName: "Precision Bushing 440C",
            catalogDescription: "440C stainless precision bushing, standard bore.",
            catalogPrice: 6.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 5,
    parseConfidence: 88,
    parseMissingFields: ["price", "dueDate"],
    ingestionSourceLabel: "Outlook - RFQ PDF",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "rfq_received",
    },
  },

  // 2. Clarification Sent — email sent to customer, awaiting reply
  {
    id: "ord-demo-004",
    orderNumber: "ORD-2026-0051",
    stage: "clarification_requested",
    source: "email",
    createdAt: "2026-03-13T09:35:00Z",
    emailSubject: "RFQ — Hydraulic fittings and seals for plant retrofit",
    customer: {
      id: "cust-demo-004",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-demo-004",
        fileName: "RFQ-Acme-Hydraulic-2026.pdf",
        mimeType: "application/pdf",
        size: 3_204,
        url: "/rfq-acme-hydraulic-2026.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-041",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 rev C",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 42.5,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 42.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-042",
        lineNumber: 2,
        rawText: "60 Pump Impeller 4in IMP-4-220 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 60,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-043",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 or SK-HT-80",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        matchStatus: "partial",
        confidence: 68,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp 400°F",
            catalogDescription: "High temperature seal kit rated to 400°F.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
          {
            catalogSku: "SK-HT-80",
            catalogName: "Seal Kit High Temp 800°F",
            catalogDescription: "High temperature seal kit rated to 800°F.",
            catalogPrice: 18.9,
            catalogUom: "kit",
          },
        ],
        issues: [
          "Temperature rating not specified — could be SK-HT-55 (400°F) or SK-HT-80 (800°F)",
          "Price differs between options ($12.40 vs $18.90)",
        ],
      },
    ],
    totalItems: 3,
    parseConfidence: 91,
    parseMissingFields: [],
    ingestionSourceLabel: "Outlook - RFQ PDF",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "rfq_received",
      clarifications: [
        {
          questions: [
            "RFQ lists 'Seal Kit High Temp' without specifying the operating temperature range — is this the SK-HT-55 (up to 400°F) or SK-HT-80 (up to 800°F)?",
            "Requested due date for Pump Impeller 4in is 2026-03-29 — can you confirm this is firm or if there is flexibility?",
          ],
          emailSent: {
            to: "james.whitfield@acmedist.com",
            subject: "ORD-2026-0051 — Clarification needed for 2 items",
            body: "Hi James,\n\nThank you for sending over the hydraulic fittings RFQ. We have a couple of questions before we can finalize pricing:\n\n1. The Seal Kit High Temp — is this the SK-HT-55 (rated to 400°F) or the SK-HT-80 (rated to 800°F)?\n2. The due date for the Pump Impeller 4in is listed as Mar 29 — is that firm?\n\nBest regards,\nHexa Sales Team",
            sentAt: "2026-03-13T09:50:00Z",
          },
        },
      ],
    },
  },

  // 3. Clarification Received — customer replied, ready for quote preparation
  {
    id: "ord-demo-001",
    orderNumber: "ORD-2026-0048",
    stage: "clarification_received",
    source: "email",
    createdAt: "2026-03-13T08:40:00Z",
    emailSubject: "RFQ-2026-1187 — Need quote for March machining lot",
    customer: {
      id: "cust-demo-003",
      name: "Elena Marsh",
      email: "elena.marsh@northfieldcomponents.com",
      phone: "(555) 220-1178",
      company: "Northfield Components",
      billingAddress: "810 Industrial Parkway, Dayton, OH 45402",
      shippingAddress: "810 Industrial Parkway, Gate 6, Dayton, OH 45402",
    },
    attachments: [
      {
        id: "att-demo-001",
        fileName: "RFQ-2026-1187-Northfield.pdf",
        mimeType: "application/pdf",
        size: 3_285,
        url: "/rfq-northfield-march-2026.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-011",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 rev C",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 42.5,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 42.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-012",
        lineNumber: 2,
        rawText: "60 Pump Impeller 4in IMP-4-220 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 60,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-013",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 rev A",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        requestedDueDate: "2026-03-30",
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp",
            catalogDescription: "High temperature seal kit.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 97,
    ingestionSourceLabel: "Outlook - RFQ PDF",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "rfq_received",
      quoteNumber: "Q-2026-0048",
      clarifications: [
        {
          questions: [
            "RFQ lists 'Seal Kit High Temp' without specifying the operating temperature range — is this the SK-HT-55 (up to 400°F) or SK-HT-80 (up to 800°F)?",
            "Requested due date for Pump Impeller 4in is 2026-03-29 — can you confirm this is firm or if there is flexibility?",
          ],
          emailSent: {
            to: "elena.marsh@northfieldcomponents.com",
            subject: "RFQ-2026-1187 — Clarification needed for 2 items",
            body: "Hi Elena,\n\nThank you for sending over the March machining lot RFQ. We have a couple of questions before we can finalize pricing:\n\n1. The Seal Kit High Temp — is this the SK-HT-55 (rated to 400°F) or the SK-HT-80 (rated to 800°F)?\n2. The due date for the Pump Impeller 4in is listed as Mar 29 — is that firm?\n\nBest regards,\nHexa Sales Team",
            sentAt: "2026-03-13T09:00:00Z",
          },
          replyReceived: {
            body: "Hi, the seal kit is the SK-HT-55 (400°F version). And yes, March 29 is firm for the impeller — we need it for a scheduled maintenance window.",
            receivedAt: "2026-03-13T09:25:00Z",
            parsedAnswers: [
              "Seal Kit is SK-HT-55 (400°F rating) — confirmed",
              "Pump Impeller due date Mar 29 is firm — scheduled maintenance window",
            ],
          },
        },
      ],
    },
  },

  // 4. Quote Sent — handwritten RFQ, quote already sent to customer
  {
    id: "ord-demo-002",
    orderNumber: "ORD-2026-0049",
    stage: "quote_sent",
    source: "email",
    createdAt: "2026-03-13T08:55:00Z",
    emailSubject: "Quick RFQ — handwritten shop-floor request",
    customer: {
      id: "cust-demo-002",
      name: "Ravi Patel",
      email: "ravi.patel@summitfab.com",
      phone: "(555) 778-4010",
      company: "Summit Fabrication",
      billingAddress: "22 Foundry Lane, Pittsburgh, PA 15201",
      shippingAddress: "22 Foundry Lane, Dock 2, Pittsburgh, PA 15201",
    },
    attachments: [
      {
        id: "att-demo-002",
        fileName: "RFQ-Summit-Handwritten-Note.pdf",
        mimeType: "application/pdf",
        size: 2_998,
        url: "/rfq-summit-handwritten.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-021",
        lineNumber: 1,
        rawText: "30 shaft collars SC-12 rev B",
        parsedSku: "SC-12",
        parsedProductName: "Shaft Collar 12mm",
        parsedQuantity: 30,
        parsedUom: "units",
        parsedUnitPrice: 6.9,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 93,
        matchedCatalogItems: [
          {
            catalogSku: "SC-12",
            catalogName: "Shaft Collar 12mm",
            catalogDescription: "Steel shaft collar, 12mm ID.",
            catalogPrice: 6.9,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-022",
        lineNumber: 2,
        rawText: "75 bearings BB-6205 rev C",
        parsedSku: "BB-6205",
        parsedProductName: "Deep Groove Bearing 6205",
        parsedQuantity: 75,
        parsedUom: "units",
        parsedUnitPrice: 4.8,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "BB-6205",
            catalogName: "Deep Groove Bearing 6205-2RS",
            catalogDescription: "Sealed bearing, both sides.",
            catalogPrice: 4.8,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-023",
        lineNumber: 3,
        rawText: "20 gasket packs GK-STD-25",
        parsedSku: "GK-STD-25",
        parsedProductName: "Standard Gasket Pack",
        parsedQuantity: 20,
        parsedUom: "packs",
        parsedUnitPrice: 11.5,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "GK-STD-25",
            catalogName: "Standard Gasket Pack",
            catalogDescription: "General purpose gasket set.",
            catalogPrice: 11.5,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 94,
    ingestionSourceLabel: "Outlook - Handwritten RFQ",
    demoFlow: {
      scenario: "rfq_handwritten",
      stage: "quote_prepared",
      quoteNumber: "Q-2026-0049",
      quoteSummary: {
        quoteNumber: "Q-2026-0049",
        items: [
          { sku: "SC-12", name: "Shaft Collar 12mm", qty: 30, unitPrice: 6.9 },
          { sku: "BB-6205", name: "Deep Groove Bearing 6205-2RS", qty: 75, unitPrice: 4.8 },
          { sku: "GK-STD-25", name: "Standard Gasket Pack", qty: 20, unitPrice: 11.5 },
        ],
        subtotal: 797.0,
        sentAt: "2026-03-13T08:40:00Z",
        sentTo: "ravi.patel@summitfab.com",
      },
    },
  },

  // 5. In Manufacturing — pushed to MRP, shipment created, awaiting production
  {
    id: "ord-003",
    orderNumber: "ORD-2026-0045",
    stage: "shipped",
    source: "email",
    createdAt: "2026-02-25T11:00:00Z",
    emailSubject: "Re: Quarterly Supply Request",
    customer: {
      id: "cust-003",
      name: "Marcus Rivera",
      email: "m.rivera@toplinehardware.com",
      phone: "(555) 321-0987",
      company: "Topline Hardware LLC",
      billingAddress: "78 Main Street, Portland, OR 97201",
      shippingAddress: "900 Distribution Way, Portland, OR 97220",
    },
    attachments: [
      {
        id: "att-003",
        fileName: "PO-2026-0299-Topline.pdf",
        mimeType: "application/pdf",
        size: 3_736,
        url: "/po-topline-supply-q1.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-020",
        lineNumber: 1,
        rawText: "500 Brass Hinges BH-SM-500",
        parsedSku: "BH-SM-500",
        parsedProductName: "Brass Hinge Small 500-Pack",
        parsedQuantity: 500,
        parsedUom: "units",
        parsedUnitPrice: 0.85,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "BH-SM-500",
            catalogName: "Brass Hinge Small - Bulk 500",
            catalogDescription: "Small brass hinges for cabinet doors, bulk pack.",
            catalogPrice: 0.85,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-021",
        lineNumber: 2,
        rawText: '25 Drawer Slides 18" DS-18-PR',
        parsedSku: "DS-18-PR",
        parsedProductName: 'Drawer Slide 18" Pair',
        parsedQuantity: 25,
        parsedUom: "pairs",
        parsedUnitPrice: 11.0,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "DS-18-PR",
            catalogName: 'Drawer Slide 18" Pair',
            catalogDescription: '18-inch full extension drawer slides, sold in pairs.',
            catalogPrice: 11.0,
            catalogUom: "pair",
          },
        ],
        issues: [],
      },
      {
        id: "li-022",
        lineNumber: 3,
        rawText: "40 cabinet knobs CK-RND",
        parsedSku: "CK-RND",
        parsedProductName: "Cabinet Knob Round",
        parsedQuantity: 40,
        parsedUom: "each",
        parsedUnitPrice: 3.25,
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "CK-RND",
            catalogName: "Cabinet Knob Round - Brushed Nickel",
            catalogDescription: "Round cabinet knob, brushed nickel finish.",
            catalogPrice: 3.25,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
      {
        id: "li-023",
        lineNumber: 4,
        rawText: "60 Soft-Close Hinges SC-35 35mm",
        parsedSku: "SC-35",
        parsedProductName: "Soft-Close Hinge 35mm Cup",
        parsedQuantity: 60,
        parsedUom: "each",
        parsedUnitPrice: 4.75,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "SC-35",
            catalogName: "Soft-Close Hinge 35mm Cup",
            catalogDescription: "35mm cup soft-close cabinet hinge, 110° opening.",
            catalogPrice: 4.75,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 4,
    poNumber: "PO-2026-0299",
    dueDate: "12 Mar 2026",
    shipTo: "900 Distribution Way, Portland, OR 97220",
    shipVia: "FedEx Economy",
    paymentTerms: "Net 30",
    parseConfidence: 96,
    parseMissingFields: [],
    mrpRoutedAt: "2026-02-25T11:01:00Z",
    ingestionSourceLabel: "email:attachment",
    shipmentSummary: {
      shipmentId: "shp-mock-003",
      status: "shipment_created",
      carrier: "fedex",
      trackingNumber: "794644790132",
      estimatedDelivery: "2026-03-18",
      latestEventAt: "2026-03-10T14:30:00Z",
    },
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0038",
      poNumber: "PO-2026-0299",
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price", matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity", matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate", matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
          { field: "drawingRev", matches: true, quoteValue: "Revisions matched", incomingValue: "Revisions matched" },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0038",
        items: [
          { sku: "BH-SM-500", name: "Brass Hinge Small 500-Pack", qty: 500, unitPrice: 0.85 },
          { sku: "DS-18-PR", name: "Drawer Slide 18\" Pair", qty: 25, unitPrice: 11.0 },
          { sku: "CK-RND", name: "Cabinet Knob Round", qty: 40, unitPrice: 3.25 },
          { sku: "SC-35", name: "Soft-Close Hinge 35mm", qty: 60, unitPrice: 4.75 },
        ],
        subtotal: 1090.0,
        sentAt: "2026-02-22T10:00:00Z",
        sentTo: "m.rivera@toplinehardware.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0299",
        receivedAt: "2026-02-24T14:30:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-02-25T11:01:00Z",
        erpOrderId: "ERP-2026-0299",
      },
      erpSync: {
        state: "acknowledged",
        timeline: [
          { label: "PO parsed from email attachment", state: "queued", at: "2026-02-25T11:00:12Z" },
          { label: "PO matched against quote Q-2026-0038", state: "sent", at: "2026-02-25T11:00:45Z" },
          { label: "ERP order acknowledged", state: "acknowledged", at: "2026-02-25T11:01:00Z" },
        ],
      },
    },
  },
];
